### ISSUE TITLE
`@segment/analytics-generic-utils` does not list `tslib` as a dependency

### ISSUE THREAD

**Issue by bencmbrook** [segmentio/analytics-next#1016]
> Error: @segment/analytics-generic-utils tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
> 
> Required package: tslib
> Required by: @segment/analytics-generic-utils@npm:1.1.0

This is not declared in [package.json](https://github.com/segmentio/analytics-next/blob/a8b2a238aeeaecf051046765dc1b3aa5c90225b1/packages/generic-utils/package.json)

<details>
  <summary>Full stack trace</summary>

Error: @segment/analytics-generic-utils tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: tslib
Required by: @segment/analytics-generic-utils@npm:1.1.0 (via /Users/my-project/.yarn/cache/@segment-analytics-generic-utils-npm-1.1.0-7dc4f2d321-6a6863f2fc.zip/node_modules/@segment/analytics-generic-utils/dist/cjs/)

Require stack:
- /Users/my-project/.yarn/cache/@segment-analytics-generic-utils-npm-1.1.0-7dc4f2d321-6a6863f2fc.zip/node_modules/@segment/analytics-generic-utils/dist/cjs/index.js
- /Users/my-project/.yarn/cache/@segment-analytics-core-npm-1.4.0-c54ad1e181-e4151e60c4.zip/node_modules/@segment/analytics-core/dist/cjs/priority-queue/index.js
- /Users/my-project/.yarn/cache/@segment-analytics-core-npm-1.4.0-c54ad1e181-e4151e60c4.zip/node_modules/@segment/analytics-core/dist/cjs/index.js
- /Users/my-project/.yarn/cache/@segment-analytics-node-npm-1.1.4-4206f1be60-5e7a49486e.zip/node_modules/@segment/analytics-node/dist/cjs/app/analytics-node.js
- /Users/my-project/.yarn/cache/@segment-analytics-node-npm-1.1.4-4206f1be60-5e7a49486e.zip/node_modules/@segment/analytics-node/dist/cjs/index.js
- /Users/my-project/.next/server/pages/api/contact.js
- /Users/my-project/.yarn/__virtual__/next-virtual-aa5138e6bb/0/cache/next-npm-14.0.2-31ca706cd2-d091d5383d.zip/node_modules/next/dist/server/future/helpers/module-loader/node-module-loader.js
- /Users/my-project/.yarn/__virtual__/next-virtual-aa5138e6bb/0/cache/next-npm-14.0.2-31ca706cd2-d091d5383d.zip/node_modules/next/dist/server/future/helpers/module-loader/route-module-loader.js
- /Users/my-project/.yarn/__virtual__/next-virtual-aa5138e6bb/0/cache/next-npm-14.0.2-31ca706cd2-d091d5383d.zip/node_modules/next/dist/export/routes/app-route.js
- /Users/my-project/.yarn/__virtual__/next-virtual-aa5138e6bb/0/cache/next-npm-14.0.2-31ca706cd2-d091d5383d.zip/node_modules/next/dist/export/worker.js
- /Users/my-project/.yarn/__virtual__/next-virtual-aa5138e6bb/0/cache/next-npm-14.0.2-31ca706cd2-d091d5383d.zip/node_modules/next/dist/build/worker.js
- /Users/my-project/.yarn/__virtual__/next-virtual-aa5138e6bb/0/cache/next-npm-14.0.2-31ca706cd2-d091d5383d.zip/node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js
- /Users/my-project/.yarn/__virtual__/next-virtual-aa5138e6bb/0/cache/next-npm-14.0.2-31ca706cd2-d091d5383d.zip/node_modules/next/dist/build/entries.js
- /Users/my-project/.yarn/__virtual__/next-virtual-aa5138e6bb/0/cache/next-npm-14.0.2-31ca706cd2-d091d5383d.zip/node_modules/next/dist/server/dev/hot-reloader-webpack.js
- /Users/my-project/.yarn/__virtual__/next-virtual-aa5138e6bb/0/cache/next-npm-14.0.2-31ca706cd2-d091d5383d.zip/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js
- /Users/my-project/.yarn/__virtual__/next-virtual-aa5138e6bb/0/cache/next-npm-14.0.2-31ca706cd2-d091d5383d.zip/node_modules/next/dist/server/lib/router-server.js
- /Users/my-project/.yarn/__virtual__/next-virtual-aa5138e6bb/0/cache/next-npm-14.0.2-31ca706cd2-d091d5383d.zip/node_modules/next/dist/server/lib/start-server.js
    at require$$0.Module._resolveFilename (/Users/my-project/.pnp.cjs:36042:13)
    at /Users/my-project/.yarn/__virtual__/next-virtual-aa5138e6bb/0/cache/next-npm-14.0.2-31ca706cd2-d091d5383d.zip/node_modules/next/dist/server/require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at require$$0.Module._load (/Users/my-project/.pnp.cjs:35933:31)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at mod.require (/Users/my-project/.yarn/__virtual__/next-virtual-aa5138e6bb/0/cache/next-npm-14.0.2-31ca706cd2-d091d5383d.zip/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/my-project/.yarn/cache/@segment-analytics-generic-utils-npm-1.1.0-7dc4f2d321-6a6863f2fc.zip/node_modules/@segment/analytics-generic-utils/dist/cjs/index.js:3:15)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at require$$0.Module._extensions..js (/Users/my-project/.pnp.cjs:36085:33)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at require$$0.Module._load (/Users/my-project/.pnp.cjs:35933:31)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
</details>

**Comment by silesky** [comment]
@bencmbrook Thank you for taking out an issue. Resolving: https://github.com/segmentio/analytics-next/issues/1016

**Comment by silesky** [comment]
This is in master but has not been published to npm. Will close once this has been released.
