### ISSUE TITLE
How to mock in e2e testing

### ISSUE THREAD

**Issue by brianabaker** [segmentio/analytics-next#1017]
Hello! We're moving off of Segment analytics loaded in our window to this analytics-next library.

For Analytics testing, we do mostly RTL unit testing & also e2e testing with Cypress (e2e only for certain flows). I'm running into some issues modifying our Cypress mocks. 

I'm not sure how to mock Segment to consider itself "initialized" like we used to when the code was on our window. I can see the mocked analytics when my code first loads (via console logs), but then they are overwritten (I think when Segment initializes). 

This is how we used to mock, is there something i can do to replicate setting `window.analytics.initialize` to true?
```
export const stubAnalytics = (win) => {
  win.analytics = win.analytics || [];

  // stops the segment script tag from executing, which would overwrite out stubs
  win.analytics.initialize = true;

  cy.stub(analytics, "track").as("analytics.track");
};
```

Thanks!

**Comment by silesky** [comment]
@brianabaker 

Wouldn't you rather just disable segment altogether for e2e testing? We have a .load({...}, { disable: true }) option.

**Comment by brianabaker** [comment]
For sure. Some code is removed from here, but it's the general idea:

```
// Our own Segment Tracker file -- missing a lot of the code but this is enough to get a feel I think

import { AnalyticsBrowser } from "@segment/analytics-next";

export const analytics = new AnalyticsBrowser();

export class SegmentService implements Service {
  track = (event: Event): Event => {

    analytics.track(name, underscorify(getProperties(event)));
    return event;
  };
}

// this gets called in another file 
export const getInstance = (): Tracker => {
  // `instance` here is an instance of SegmentService, our own class above!
  if (!instance) {
    const segmentWriteKey = process.env.KEY;
    const allowAnalytics = window?.doNotTrack !== true;

    analytics
      .load(
        { writeKey: `${segmentWriteKey}` },
          // i added disable: true here temporarily to try and help mock, it didn't assist.
        { integrations: { All: allowAnalytics }, disable: true },
      )
      .catch((e: Error) => console.error("Error loading Segment", e));
    instance = new SegmentService();
  }

  return instance;
};
```

**Comment by silesky** [comment]
@brianabaker It sounds like `disable` is not what you're after, since you're actually attempting to assert that analytics are being sent, correct? 

You would want HTTP request interception if you need that level of e2e-'ness' -- this Playwright example should get you started:

https://github.com/segmentio/analytics-next/blob/master/packages/browser-integration-tests/src/index.test.ts

**Comment by brianabaker** [comment]
@silesky Okay, thank you! Interestingly I still saw Segment API calls with `disable: true`. Those should have not taken place in my tests, yeah?
