### ISSUE TITLE
Amplitude Integration not loading correctly

### ISSUE THREAD

**Issue by Dgiulian** [segmentio/analytics-next#1029]
I have the Amplitude Integration configured in Segment. But it's not loading correctly using  `@segment/analytics-next`. 

When I track an event the payload includes this metadata

```json

"_metadata": {
    "failedInitializations": [
      "Amplitude"
    ],
    "bundled": [
      "Amplitude",
      "Intercom",
      "Segment.io"
    ],
    "unbundled": [],
    "bundledIds": [
      ".....",
      "....."
    ]
}
```

this is the code I'm using to load Segment:

```js
  const [analytics] = useState(
    import.meta.env.VITE_SEGMENT_KEY
      ? AnalyticsBrowser.load({
          writeKey: import.meta.env.VITE_SEGMENT_KEY,
        })
      : undefined,
  );
```

After checking in Segment I can see the event being tracked, but it's not getting through to Amplitude.

I can see the `https://cdn.segment.com/v1/projects/<WriteKey>/settings` being called and includes the correct Amplitude `apiKey`.

The console is showing this error when Segment loads:

![image](https://github.com/segmentio/analytics-next/assets/644747/531f0408-e3f5-4fa6-b602-c3ed40b04c32)

**Comment by silesky** [comment]
@Dgiulian, sorry you're having an issue.

Can you take out a support ticket through the Segment website? This repo does not include the actual [action destinations](https://github.com/segmentio/action-destinations) themselves.
