### ISSUE TITLE
Blink display on loading segment library

### ISSUE THREAD

**Issue by pkolt** [segmentio/analytics-next#1030]
Hi guys!

I use Next.js 14 and I watch one problem on loading segment library.

While loading the segment library, for some reason the CSS property opacity is set to `0` for `body` (HTML element).

This causes the content to momentarily disappear. On dark themes it looks like the screen is blinking.

https://github.com/segmentio/analytics-next/assets/478905/776a64c3-0769-4e96-bf21-69ac3e13bbde

I am sure that the problem is in the segment library, and not in something else, because it is the segment code that changes the transparency properties.

<img width="1512" alt="Screenshot 2024-01-25 at 16 08 19" src="https://github.com/segmentio/analytics-next/assets/478905/6eedc9cd-d675-496b-b67c-4fbc07dc4ae3">
<img width="1512" alt="Screenshot 2024-01-25 at 16 06 48" src="https://github.com/segmentio/analytics-next/assets/478905/a30679e2-33be-4158-821c-d825151ee5e9">

**Comment by silesky** [comment]
Hi! This is an integration maintained by VWO on the segment action destination repo. Can you take out a support ticket on vwo.com?

**Comment by pkolt** [comment]
@silesky OK, thank you!
