### ISSUE TITLE
Rare Context2 in Nuxt 3 

### ISSUE THREAD

**Issue by agracia-foticos** [segmentio/analytics-next#1040]
We have this environment
https://stackblitz.com/edit/nuxt-starter-juxjq4

When i use segment into a Nuxt 3 composable, the object into the composable and outthere its diferent!!!

![image](https://github.com/segmentio/analytics-next/assets/77386602/1dfcb10e-9a1c-476f-90c9-9202805d35c5)

**Comment by silesky** [comment]
AnalyticsBrowser instances are a thenable (originally, this was an async API and we added sync support afterward).

```ts
const analyticsBrowser = new AnalyticsBrowser() // this is buffered
const [analytics, context] = await analyticsBrowser // this is the underlying, initialized analytics
```

We recommend you don't `await`.
```ts
const segment = await useSegment();  // don't do this
const segment = useSegment();  // do this
```
