### ISSUE TITLE
Consent module pollutes logs when using OneTrust's "Consent Rate Optimization" feature. 

### ISSUE THREAD

**Issue by backjo** [segmentio/analytics-next#1049]
When using OneTrust's 'Consent Rate Optimization' feature, they ask you to populate the OneTrust global object in the following shape:

```js
window.OneTrust = {"id":"423070798","isAnonymous":false,"token":"<someJWT>"}})
```

This is causing a lot of log noise due to this validation error -> https://github.com/segmentio/analytics-next/blob/50a969bacc943abb4bd52ec158a66babf426beef/packages/consent/consent-wrapper-onetrust/src/lib/onetrust-api.ts#L64

**Comment by silesky** [comment]
Fixed in https://github.com/segmentio/analytics-next/releases/tag/%40segment%2Fanalytics-consent-wrapper-onetrust%400.4.1
