### ISSUE TITLE
Snippet version 5.2.0 loads analytics.min.js and analytics.classic.js at the same time

### ISSUE THREAD

**Issue by seg-leonelsanches** [segmentio/analytics-next#1057]
Source ID: 8ReQDBigstiGzXQz9UVBUM
Snippet version: 5.2.0
Evidence: 

![Analytics.js loaded twice](https://github.com/segmentio/analytics-next/assets/113376080/0bd0c119-10c5-4130-af2b-5ebb51663f9b)

Workaround: Customer downgraded to snippet version 4.15.3.

**Comment by silesky** [comment]
can't reproduce
