### ISSUE TITLE
How to Set a Whitelist of Domains for a Segment JavaScript source WriteKey to Prevent Misuse?

### ISSUE THREAD

**Issue by naviangie** [segmentio/analytics-next#1059]
I'm concerned about the potential for the writeKey to be extracted and misused by third parties on unauthorized domains.

Is there a way to configure a whitelist of domains through any settings in the analytics service, which would only allow my writeKey to be used from specific, authorized domains I designate?

**Comment by silesky** [comment]
Sorry, that's not a thing that Segment supports. 

I responded to a similar issue here:
https://github.com/segmentio/analytics-next/issues/1050#issuecomment-2004604183
