### ISSUE TITLE
Typescript issue on consent object of CoreExtraContext type

### ISSUE THREAD

**Issue by philibea** [segmentio/analytics-next#1060]
As we start adding the consent management on our configuration actually there is no consent type on `CoreExtraContext` https://github.com/segmentio/analytics-next/blob/master/packages/core/src/events/interfaces.ts#L50

i wonder if it was normal as i find how to configure the consent middleware on a javascript project: https://github.com/segmentio/consent-manager/blob/f9d5166679b3c928b394b8ad50d517fdf43654b1/src/consent-manager-builder/analytics.ts#L20 and with a typescript project you will have type error on any.

Maybe there is better way do to that but this clearly missing of documentation on the website.

Do we need to use this wrapper https://github.com/segmentio/analytics-next/blob/master/packages/consent/consent-tools/README.md

**Comment by silesky** [comment]
CoreExtraContext has a very loose index signature that should mean you don't get any TypeScript errors -- for better or for worse. I think that magic consent property may have been experimental / internal, so perhaps it was deliberately undocumented-- I don't have strong opinions.
 
Segment Consent Manager is confusingly, not actually related to our consent manager library in this repo. They actually using different APIs (you can see the middleware that consent tools uses). Segment Consent Manager is a simple GUI consent manager that uses hardcoded categories per integration, whereas the consent management solution in this repo is meant to be a flexible solution that works with OneTrust, TrustArc, or even a home-rolled consent manager. The app consent dashboard only works with this library.

A different team own Segment Consent Manager -- so if you have questions specific to them, I would recommend taking out issues in their repo.
