### ISSUE TITLE
@segment/analytics-consent-wrapper-onetrust README code sandbox link looks incorrect

### ISSUE THREAD

**Issue by mwisner** [segmentio/analytics-next#1078]
Hi,

I just wanted to mention that the Nextj.Js codesandbox link in the readme looks to be incorrect? The link goes here:  https://codesandbox.io/p/devbox/focused-bhaskara-jysqr5

which looks like a blank nextjs v12 example without any segment / onetrust code.

**Comment by silesky** [comment]
@mwisner, thanks! I guess it all got wiped, and I don't see a way to recover 😢 

Will just delete that link.
