### ISSUE TITLE
Cannot install package via NPM

### ISSUE THREAD

**Issue by sofly** [segmentio/analytics-next#1087]
Cannot install package via NPM

node@v20.12.2
npm@10.7.0

Logs:
[2024-05-07T13_44_36_131Z-debug-0.log](https://github.com/segmentio/analytics-next/files/15236447/2024-05-07T13_44_36_131Z-debug-0.log)

**Comment by caribou-code** [comment]
I have the same problem. Possibly specific to Node 20?

**Comment by MustafaLeanTech** [comment]
Check this answer [here](https://github.com/segmentio/analytics-next/issues/1044#issuecomment-2037187196), it helped me

**Comment by caribou-code** [comment]
> Check this answer [here](https://github.com/segmentio/analytics-next/issues/1044#issuecomment-2037187196), it helped me

Thanks, this is what I did in the end and it worked, but the issue still needs fixing in this package.

**Comment by stefco** [comment]
Still an issue

**Comment by hannahlaek-wt** [comment]
Still a problem

**Comment by silesky** [comment]
Sorry guys, trying to get bandwidth to solve this this quarter. It's related to the node-gyp dependency by tsubjs.

**Comment by silesky** [comment]
Fixed in 1.72.0
