### ISSUE TITLE
How to write an enrichment plugin that fires after a remote integration?

### ISSUE THREAD

**Issue by kwalker3690** [segmentio/analytics-next#1120]
I'm writing an 'enrichment' plugin that should add a property to any event that comes through `track`. However, the value of this property relies on a value added to events via an integration (the Amplitude Actions integration to be specific). Here is the code I'm using to register my plugin:

```
const testPlugin: Plugin = {
  name: "Session Replay Events",
  type: "enrichment",
  version: "1.0.0",

  isLoaded: () => true,
  load: loadMethod,
  track: trackMethod,
};

SegmentAnalytics.load({
  writeKey: <api key>,
  plugins: [testPlugin],
});
```

When debugging this, I've inspected the code and observed that `testPlugin` (red arrow in below screenshot) is always added before the Actions enrichment plugin (blue arrow in below screenshot)

![Screenshot 2024-07-22 at 2 20 39 PM](https://github.com/user-attachments/assets/25480190-9566-4eef-b5f0-24d9aa24f363)

I believe the ordering is occurring due to the ordering of `plugins` vs `remotePlugins` in [this code snippet](https://github.com/segmentio/analytics-next/blob/master/packages/browser/src/browser/index.ts#L285-L287).

I'd like to have my plugin be registered in load() so that we can enrich all events, including those emitted immediately on page load (as opposed to registering my plugin after load(), which means it will not capture those initial events).

Because of the ordering, when I console log via my `track` method, the `ctx.event.integrations` object is empty, as the Amplitude Actions integration has not yet been processed:
![image](https://github.com/user-attachments/assets/34a4dc94-d35a-4544-bb7c-cc4506d83964)

**Is there any way I can have my testPlugin be registered in `load()`, but have its track calls execute after those from remotely loaded plugins?**

**Comment by silesky** [comment]
@kwalker3690 thanks for the level of detail. QQ: you try type: after instead of type: enrichment?

**Comment by silesky** [comment]
@kwalker3690 That is odd behavior -- that for a given plugin, you would expect .load to _always_ resolve before any of its methods are called.

I think there's a pattern that works, however: can we do something like this?

```ts
  class MyPlugin implements Plugin {
    readonly type = "enrichment";
    readonly name = "Enrichment Plugin";
    readonly version = "0.0.0";
    public data!: Promise<string> 
    
    async load() {
      
      // fetch async data
      this.data = new Promise((resolve) => setTimeout(() => resolve('data'), 1000));
      
      return Promise.resolve();
    }
    
    private async enrich(ctx: Context) {
      ctx.event.context!.data = await this.data;
      console.log('enriched context:', ctx.event.integrations)
    }

    isLoaded() {
      return true;
    }
    
    async track(ctx: Context) {
      await this.enrich(ctx);
      return ctx
    }
    
    async page(ctx: Context) {
      await this.enrich(ctx);
      return ctx
    }
    
    async alias(ctx: Context) {
      await this.enrich(ctx);
      return ctx 
    }
    
    async identify(ctx: Context) {
      await this.enrich(ctx);
      return ctx
    }

     async screen(ctx: Context) {
      await this.enrich(ctx);
      return ctx
    }
  }
```

**Comment by kwalker3690** [comment]
Amazing - I need to do a little more validation but at first glance I think this approach should do the trick! Thanks for working through this with me
