### ISSUE TITLE
Support `exactOptionalPropertyTypes` in TypeScript

### ISSUE THREAD

**Issue by mrmckeb** [segmentio/analytics-next#1138]
This is a quick change, and I'm happy to contribute.

When using TypeScript with [`exactOptionalPropertyTypes`](https://www.typescriptlang.org/tsconfig/exactOptionalPropertyTypes.html), we get errors because Segment types don't allow `undefined` to be supplied to optional values.

The fix is that whenever a type is optional, it should also allow undefined.

As an example:
```diff
export type TrackParams = {
  event: string
-  properties?: EventProperties
+  properties?: EventProperties | undefined
-  context?: ExtraContext
+  context?: ExtraContext | undefined
-  timestamp?: Timestamp
+  timestamp?: Timestamp | undefined
-  integrations?: Integrations
+  integrations?: Integrations | undefined
-  messageId?: string
+  messageId?: string | undefined
} & IdentityOptions
```

**Comment by silesky** [comment]
@mrmckeb makes sense, happy to have a PR for this. Thanks!

**Comment by mrmckeb** [comment]
I took a look at this and I saw two options:
1. Codemod the whole codebase, so that every "optional" value accepts undefined - I have that mostly done, but it's a big PR.
2. Change only what we need, and over time, other people can create PRs if they find additional areas where they'd like to have `undefined` supported.

Either option will likely require more changes over time, as option 1 still won't prevent new code from being added that doesn't include `undefined` when the type is optional.

What do you think @silesky?

**Comment by silesky** [comment]
@mrmckeb -- definitely the one with the least amount of code changes, that ideally only touches the public APIs (i.e. Params). Thanks!

**Comment by mrmckeb** [comment]
Done - sorry it took so long @silesky!
https://github.com/segmentio/analytics-next/pull/1156
