### ISSUE TITLE
Beacon API support

### ISSUE THREAD

**Issue by erykpiast** [segmentio/analytics-next#1167]
Did you consider adding support for the Beacon API as a "transport layer" alternative to `fetch`/`XHR`? This native API is created with analytics in mind and helps increasing reliability of client-side data collection.

To quote [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API).
>The Beacon API is used to send an asynchronous and non-blocking request to a web server. The request does not expect a response. Unlike requests made using [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) or the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), the browser guarantees to initiate beacon requests before the page is unloaded and to run them to completion.

Nowadays [the browser support for Beacon API is excellent](https://caniuse.com/beacon) (96%+), from my perspective is a no-brainer.

To give you an example of what it could help with practically - checkout flows provided externally, e.g. by Stripe. Imagine you have a payment plan selection in your webapp, but the payment itself happens on a different domain. Measuring the conversion - a ratio of clicks on the "Checkout" button in your app and successful payment - it's quite difficult with regular async HTTP requests as they're interrupted when the page unloads. If you redirect to an external domain right in the button click handler and you don't wait for the analytics request to finish, the risk of missing an event is quite high. Delaying the redirection it is not ideal, as it degrades user experience. Beacon API would solve this issue ultimately. 

I wonder if there are any concerns about having this as an option? I found [this comment from @f2prateek](https://github.com/segmentio/analytics.js/issues/565#issuecomment-390284709) mentioning Beacon API and _some reasons_ to not introduce it. Apart from that, no serious take on it there and no mention whatsoever in this repository, which is quite surprising.

**Comment by silesky** [comment]
Hey @erykpiast. I wasn't around for the discussion, but IIRC `sendBeacon` has body size limitations in browser that are potentially problematic, which is also why we don't use keep-alive except when using the batched dispatcher.  By default, we send events as soon as they enter the Segmentio plugin (one at a time), so it's not *obvious* sendBeacon support would add a ton of resilience, and has potential downsides.  If we were batching data by default, it would be more pertinent.

There's no reason IMO that it couldn't be an option, but I'd love to see some actual real-world tests that showed that it substantially improved event resillience.

**Comment by erykpiast** [comment]
Hey @silesky, thanks for your answer! That's strange I didn't get a notification about it.

I had no idea about the keep alive option! It was quite well hidden in the docs. [I found a mention of it here](https://github.com/segmentio/analytics-next/issues/768#issuecomment-1430215892) now when you mentioned it. Do I get it right, that I need to enable it for all requests? I think this should be fine, but originally I was thinking about tagging one particular track call as "possibly interrupted". That's my use case after all - I know well which event doesn't get in because of the hard page reload.
