### ISSUE TITLE
Setting custom domain when using a proxy

### ISSUE THREAD

**Issue by patbegg** [segmentio/analytics-next#285]
Hi 👋
We're using a proxy for `analytics.js` following the Segment guidelines. In the classic version it was possible to set the domain using `apiHost`. What's the correct way of doing this using analytics-next? 

We're working around it by setting `window.analytics._cdn = 'https://my.custom-domain.com'` before calling `AnalyticsBrowser.load(writeKey)`.

I'm sure there is a better way but couldn't work it out looking through the code.

Appreciate any help.

**Comment by nettofarah** [comment]
Hey, @patbegg.
You should be able to set `._cdn` if you're on the latest snippet:
https://github.com/segmentio/snippet/pull/79

**Comment by nettofarah** [comment]
cc @juliofarah to give you more context on the change

**Comment by juliofarah** [comment]
Hi @patbegg 
thanks for opening this issue!

Short answer is yes, the `._cdn` property is sill the way to go!

Long answer, as @nettofarah mentioned, we have shipped a new version of the snippet last week that includes the `._cdn` property. If you set the CDN Host field on the source config page (see screenshot), the Segment app will generate the snippet containing the `._cdn` property - you can find it on the source config page.

![image](https://user-images.githubusercontent.com/484013/134952725-1260605a-bf8a-4b1e-a96b-17f331fb43bb.png)
![image](https://user-images.githubusercontent.com/484013/134952920-5ca9293c-28c3-43ee-b649-cc30338c135f.png)

**Comment by patbegg** [comment]
That's good to hear. Being able to alias from the Segment UI will be great, thanks @nettofarah @juliofarah
