### ISSUE TITLE
[Question] NextJS Integration

### ISSUE THREAD

**Issue by yordis** [segmentio/analytics-next#298]
Hey folks 👋🏻 , any example of how to integrate with NextJS?

Cheers,

**Comment by pooyaj** [comment]
Hey @yordis, our [example App ](https://github.com/segmentio/analytics-next/blob/master/example/pages/index.tsx) is a NextJS application. Could you please check it out, and if still not straight-forward, happy to write-up a guide/update the docs.

**Comment by yordis** [comment]
Niiiice, let me take a look, thank you so much

**Comment by yordis** [comment]
@viktor-edgardcooper I understand that.

But from my perspective, I am just importing an NPM package, so I would expect it to work `unless`, we are entering the realm of Python 2 vs 3 where we should start embracing ESM over everything 😄 just want to understand the situation.

**Comment by pooyaj** [comment]
@yordis thanks for the patience. The `1.31.0` now supports CommonJS. Let me know if still seeing the problem.

**Comment by yordis** [comment]
@pooyaj will this package become regular `@segment/analytics` or something like that? (without the `-next`)

**Comment by pooyaj** [comment]
@yordis Yes, this will be the `analytics.js` going forward. This repository will be compiled to two targets, UMD to be uploaded to `cdn.segment.com` and be used in the snippet based approach, and the ESM/CJS for the `npm` usage. We won't be renaming this package, so the name will remain `analytics-next`.

**Comment by yordis** [comment]
@pooyaj perfect, hopefully I dont forget to switch it at some point LOL
