### ISSUE TITLE
Self-hosted/Standalone Implementation

### ISSUE THREAD

**Issue by skene** [segmentio/analytics-next#304]
I've been looking through the next analytics repo to set up a self-hosted implementation of the analytics repo and it seems all initialization entry points lead to loading the legacy settings from segment API. Is it possible to the settings directly without the hitting the API and load the integrations from the modules themselves without loading them from the CDN?

Thanks in advanced.

**Comment by skene** [comment]
That would be awesome, appreciate it.

**Comment by jflayhart** [comment]
+1. We have issues with ad blockers and Content Security Policies potentially blocking segment outright. Would prefer to host this in first party context, but I know your library changes dynamically based on integrations changing via your GUI.

I like what [GTM Tagging Server](https://developers.google.com/tag-platform/tag-manager/server-side) does to fix this.
