### ISSUE TITLE
[Propose] Convert Repo to mono-repository setup

### ISSUE THREAD

**Issue by yordis** [segmentio/analytics-next#310]
Things like from the docs, 

```tsx
  const [analytics, setAnalytics] = useState<Analytics | undefined>(undefined)
  const [writeKey, setWriteKey] = useState('<YOUR_WRITE_KEY>')

  useEffect(() => {
    const loadAnalytics = async () => {
      let [response] = await AnalyticsBrowser.load({ writeKey })
      setAnalytics(response)
    }
    loadAnalytics()
  }, [writeKey])
```

Could be shared under `@segment/analytics-react` or something like that, so maybe convert the package into a mono-repository so we can collaborate in the subject matter.

I am currently doing early adoptions, so I can take some ownership on proposing some solutions based on our existing setup.

**Comment by pooyaj** [comment]
Hey @yordis, are you suggesting building a native React implementation ( e.g., a `useSegmentAnalytics` hook for example ) that abstracts away the library usage?

**Comment by yordis** [comment]
@pooyaj for the most part, my way to do things is "one function at the time, you make it declarative", that means, one function removed would allow me to be closer to bare-metal way to do things.

So yes, most of the time, they are more declarative abstractions for a given use-case, with given constraints that could tackle the 95% of the use cases, for the rest of 5%, just show people how to go one-level below.


Here is my working setup,

```tsx
import * as React from 'react';
import { Analytics, AnalyticsBrowser, Context as TContext } from '@segment/analytics-next';
import { useQuery } from 'react-query';
import { AnalyticsSettings, InitOptions } from '@segment/analytics-next/src/analytics';
import { UseQueryOptions } from 'react-query/types/react/types';

type OmittedQueryOption =
  | 'queryKey'
  | 'select'
  | 'queryFn'
  | 'refetchOnMount'
  | 'refetchOnReconnect'
  | 'refetchOnWindowFocus';

type UseSegmentAnalyticsProps = {
  options?: Omit<
    UseQueryOptions<[Analytics, TContext], unknown, { analytics: Analytics; context: TContext }>,
    OmittedQueryOption
  >;
  settings: AnalyticsSettings;
  initOptions?: InitOptions;
};

function useSegmentAnalytics(props: UseSegmentAnalyticsProps) {
  const query = useQuery<[Analytics, TContext], unknown, { analytics: Analytics; context: TContext }>({
    ...(props.options ?? {}),
    queryKey: ['@segment/analytics-next/analytics-browser/load', props.settings.writeKey],
    refetchOnMount: false,
    refetchOnReconnect: false,
    refetchOnWindowFocus: false,
    select(data) {
      return {
        analytics: data[0],
        context: data[1],
      };
    },
    queryFn() {
      // @ts-ignore
      return AnalyticsBrowser.load(props.settings, props.initOptions ?? {});
    },
  });

  return {
    isReady: query.isSuccess,
    analytics: query.data?.analytics,
    context: query.data?.context,
  };
}

const Context = React.createContext<ReturnType<typeof useSegmentAnalytics>>(undefined);

export function useSegmentAnalyticsContext() {
  return React.useContext(Context);
}

type SegmentAnalyticsV2Props = React.PropsWithChildren<UseSegmentAnalyticsProps>;

export function SegmentAnalytics(props: SegmentAnalyticsV2Props) {
  const query = useSegmentAnalytics(props);
  return <Context.Provider value={query}>{props.children}</Context.Provider>;
}
```

Obviously ignore the React Query stuff, since we have it in our system, no point in dealing with `isLoading`, and `isError` and things like that, since React Query works with any Promise.

You would swap that with something basic, I can make it to work. Hopefully, you get the idea.

**Comment by yordis** [comment]
Also notice I had to do the following import:

```ts
import { AnalyticsSettings, InitOptions } from '@segment/analytics-next/src/analytics';
```

I was thinking eventually ones it is in prod, some ticket to expose that from `@segment/analytics-next` instead.

**Comment by yordis** [comment]
Alright, dont do what I did around React Query: https://github.com/segmentio/analytics-next/issues/310#issuecomment-956774796

If by any chance you need to reset the cache of React Query (for example when using logout), you will be asking for trouble.

**Comment by silesky** [comment]
@yordis This is on the roadmap for this quarter.

**Comment by yordis** [comment]
Do you need any help? By now I am in auto-pilot doing these grunt work 😄 happy to help

**Comment by silesky** [comment]
This is done! Thanks @yordis.
