### ISSUE TITLE
Proxy HTTP(s) Calls

### ISSUE THREAD

**Issue by KevinMFinch** [segmentio/analytics-next#312]
Is there any way to configure analytics-next to point to your own hosted proxy of the Segment API? It seems like the iOS library has [this capability](https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/#proxy-https-calls) and I was wondering if this library has a way to do that.

**Comment by pooyaj** [comment]
Hi @KevinMFinch, are you using the `npm` package or using the version from `cdn.segment.com`?

**Comment by KevinMFinch** [comment]
> Hi @KevinMFinch, are you using the `npm` package or using the version from `cdn.segment.com`?

Hi @pooyaj currently I'm using the `npm` package

**Comment by pooyaj** [comment]
Cool, when using the `npm` version, you can pass the custom API host like this: 
```
... await AnalyticsBrowser.load({ writeKey: YOUR_WRITE_KEY }, {
        integrations: {
          'Segment.io': { apiHost: "api.yourcustomurl.com/v1" },
        }
      })
```

**Comment by ajayjaggi97** [comment]
Hey @pooyaj .
Can we also pass the custom headers as well. We want to change the "content-type" also.
