### ISSUE TITLE
Logger being blocked by adblocker

### ISSUE THREAD

**Issue by segerpeter07** [segmentio/analytics-next#314]
Hello,
Recently we've run into a lot of problems with Segment being blocked by adblockers (particularly the built-in ones on the Brave browser) while this library. It manifests itself as errors like these (which we're working on a fix to handle gracefully):
```
Cannot read properties of undefined (reading 'identify')
```
as we call it like this 
```
window.analytics.identify(...)
```

We are fairly certain that the "mounting logic" is being called and our logger is initially made available. We're wrapping our `_app.tsx` in a `SegmentProvider` that handles this logic as following:
`SegmentProvider.tsx`
```
export const SegmentProvider: React.FC<SegmentProviderProps> = ({ children }) => {
  const SEGMENT_WRITE_KEY = process.env.SEGMENT_WRITE_KEY!;
  const plugins: Plugin[] = process.env.NODE_ENV !== "production" ? [debugLogger] : [];

  useEffect(() => {
    const loadAnalytics = async (): Promise<void> => {
      let [response] = await AnalyticsBrowser.load({ writeKey: SEGMENT_WRITE_KEY, plugins });
      (window as any).analytics = response;
      // eslint-ignore-next-line no-console
      console.log("✅ Segment logger initiated");
    };
    loadAnalytics();
  }, [SEGMENT_WRITE_KEY]);

  return <Box id="segment-provider">{children}</Box>;
};
```
`_app.tsx`
```
...
<SegmentProvider>
    <Component {...pageProps} />
</SegmentProvider>
...
```

Any insights, best practices, etc. would be greatly appreciated!

**Comment by pooyaj** [comment]
Hi @segerpeter07, do you see that the `window.analytics` ends up being undefined with ad-blockers/brave? In other words on this line:
```
let [response] = await AnalyticsBrowser.load({ writeKey: SEGMENT_WRITE_KEY, plugins });
```
Do you get an undefined `response`?

**Comment by segerpeter07** [comment]
It actually totally fails to perform the `load` request with this error. We also get a `ERR_BLOCKED_BY_CLIENT` network error.
![image](https://user-images.githubusercontent.com/9158783/140565539-57eb85d0-e00a-43c4-88d0-11c118703b6b.png)

Thanks for looking into it @pooyaj!

**Comment by pooyaj** [comment]
@segerpeter07 seems like that the `cdn.segment.com` is being blocked, and the the library can't load the settings. No straightforward solution here, other than going for a [proxy](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/custom-proxy/).
