### ISSUE TITLE
Uncaught TypeError: can't redefine non-configurable property "metadata"

### ISSUE THREAD

**Issue by gioker10** [segmentio/analytics-next#326]
Hello,

Our Sentry integration has caught multiple of the above mentioned error. This seems to happen on multiple versions of Firefox ranging from v60 to v93. Also, the users seem to be using Linux. 

I have tried reproducing this on my machine, but to no avail. Furthermore, the stacktrace in Sentry states the error is coming from our app, but we have no property "metadata" in our code. 

Any thoughts or insight would be appreciated.

Thank you!

**Comment by pooyaj** [comment]
Hi @gioker10! Just did a quick search of the AJS codebase and couldn't find any `metadata` property either. Not sure what it could be.
