### ISSUE TITLE
Add @types/jquery as dependency

### ISSUE THREAD

**Issue by squirly** [segmentio/analytics-next#337]
## Issue

When using this repo in a TypeScript project that does not include jquery, the TypeScript compiler has an error:

```
../node_modules/@segment/analytics-next/dist/pkg/core/auto-track.d.ts:1:23 - error TS2688: Cannot find type definition file for 'jquery'.

1 /// <reference types="jquery" />
```

This is because this project's compiled TypeScript definitions depends on jquery, specifically `@types/jquery`.

## Solution

Move `@types/jquery` from `devDependencies` to `dependencies`.

**Comment by chrisradek** [comment]
@squirly Thanks for logging this issue!

I'm currently investigating if we can get away with a shim to avoid depending on `@types/jquery` directly. There is a `tsconfig.json` option, `skipLibCheck` that if set to `true` will prevent erroring on this but the types for `LinkArgs` ends up resolving to `any` if `@types/jquery` isn't present in that case.
