### ISSUE TITLE
Custom integration with analytics-next

### ISSUE THREAD

**Issue by jean-moldovan** [segmentio/analytics-next#341]
Hello,

I've been investigating the possibility of using the custom integration for Analytics-next.

It appears that I can only use the ones listed here: https://github.com/segmentio/analytics.js-integrations/tree/master/integrations and they are loaded from the Segment CDN on analytics init.

Would it be possible to use a completely custom integration without submitting it to https://github.com/segmentio/analytics.js-integrations/tree/master/integrations?

Thanks!

**Comment by pooyaj** [comment]
Hi @jean-moldovan, yes, possible. You need to write a plugin, and register it with the `analytics.next` ... check this out for the instructions: https://github.com/segmentio/analytics-next#-plugins

**Comment by jean-moldovan** [comment]
Hi @pooyaj ,
Thanks for your reply.

I'm not sure I completely understand the difference between Plugins vs Integrations. Plugins are just like integrations, but more flexible and with a better API? Does that mean that all integrations will eventually be deprecated and converted into plugins?

Let me explain my use case a bit more. I have a modified segmentio integration (basically a fork) that I was using with Analytics.js v1. If I understand correctly all integrations are backward compatible and can be used with Analytics-next (in fact, I think they are transformed into plugins via some internal adapter)? That means, that, if there was a way to register a custom integration, I could avoid refactoring it into a plugin (at least for the time being).

Hope this makes sense.

**Comment by pooyaj** [comment]
Plugins are new way to extend the behavior of analytics.js, and they can be used for integrations ( destinations ), validation, enrichment of the payload, etc. The old integrations are wrapped into plugins to make them work with AJS 2.0 ( it is done [here](https://github.com/segmentio/analytics-next/blob/e798c4d9d0998426751c7a1862076af096d32ae5/src/browser.ts#L140-L146) ). 

I think in your particular use-case, it might be possible to use import and use [ajs-destination](https://github.com/segmentio/analytics-next/blob/master/src/plugins/ajs-destination/index.ts) to use your custom Segment.io plugin, but then you are relying on private APIs, and the solution could get hacky. Probably easiest path forward would be to convert the custom integration to a plugin ( or possibly apply your customizations to [the new Segment.io](https://github.com/segmentio/analytics-next/tree/master/src/plugins/segmentio) plugin.

**Comment by jean-moldovan** [comment]
@pooyaj , Thanks for clarification 👍
