### ISSUE TITLE
Querystring `ajs_uid` is not decoded when passed to identify

### ISSUE THREAD

**Issue by troex** [segmentio/analytics-next#342]
Hi, we use email as User ID and want to use querystring api, but what happens if I send customers to `https://example.com/?ajs_uid=some@example.org` it often ends on `https://example.com/?ajs_uid=some%40example.org` because web-server or app redirect to encoded url, it results that identify is fired for `some%40example.org` however the url parameter is still `some@example.org` if accessed properly using `URLSearchParams`.

I expect that analytics.js should be able to decode url params properly.

**Comment by zikaari** [comment]
This will be addressed by #363
