### ISSUE TITLE
Error: [vite]: Rollup failed to resolve import "tslib"

### ISSUE THREAD

**Issue by kamui** [segmentio/analytics-next#346]
Using vite, I get this error when trying to start my Express server:

```
Error: [vite]: Rollup failed to resolve import "tslib" from "node_modules/@segment/analytics-next/dist/pkg/analytics.js".
```

It seems like `tslib` is a [devDependency](https://github.com/segmentio/analytics-next/blob/master/package.json#L123) and in `dist/pkg/analytics.js` `tslib` is being imported on line 1:

```
import { __awaiter, __extends, __generator, __spreadArrays } from "tslib";
```

I'm guessing this vite/Rollup error is due to the devDependency not being available when it's referenced in my app? Adding `tslib` to my app's dependencies fixes the issue, but maybe it should be a non dev dependency in `analytics-next`?

**Comment by chrisradek** [comment]
@kamui Thanks for reporting this issue! You're right, `tslib` should be a direct dependency. Created #347 to address this.
