### ISSUE TITLE
Uncaught Error: Module "stream" has been externalized for browser compatibility and cannot be accessed in client code.

### ISSUE THREAD

**Issue by kamui** [segmentio/analytics-next#353]
I'm using `vite` with `analytics-next@1.33.0`. This error message shows up in the console when I'm in dev mode trying to load `analytics-next`.

`vite` doesn't polyfill nodejs modules and `node-fetch` requires [node:stream](https://github.com/node-fetch/node-fetch/blob/main/src/index.js#L12).

`analytics-next` loads [src/node](https://github.com/segmentio/analytics-next/blob/master/src/node.ts#L4) which requires and [loads node-fetch](https://github.com/segmentio/analytics-next/blob/master/src/plugins/analytics-node/index.ts#L4).

I'm not exactly sure what `analytics-node` is. I'd guess it's a node wrapper so you can call `analytics-next` from node server side? Anyhow, is there a way to make the plugin optional as well as the node-fetch dependency for analytics-next?

**Comment by chrisradek** [comment]
@kamui Thanks for reporting this issue. Can you share what your vite config looks like, what version of vite you're using, and how you're importing analytics-next?

I haven't been able to reproduce the issue using a very basic react sample with vite:

__vite.config.ts__
```ts
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()]
})

```

Unless `AnalyticsNode` is being imported it should be tree-shaken out, so any details you can share to help me reproduce would be really helpful!

**Comment by Jarrku** [comment]
Hello!

Also ran into this issue. Here is a minimal StackBlitz reproduction:
https://stackblitz.com/edit/vite-whjr6x?devtoolsheight=33&file=main.js

**Comment by chrisradek** [comment]
@Jarrku Thanks for the repro! I am able to see the same issue when running `npm run dev` with your example.

**Comment by chrisradek** [comment]
Created #354 to fix this issue. Thanks for bringing this to our attention!
