### ISSUE TITLE
Expose Callback

### ISSUE THREAD

**Issue by yordis** [segmentio/analytics-next#355]
Related to: https://github.com/segmentio/analytics-next/issues/311#issuecomment-1006807679

Doing the following,

```ts
// Notice the Callback usage
export function analyticsTrack<TProperties = object | Callback>() {
  const analyticsContext = useSegmentAnalyticsContext();
  return (eventName: string, properties?: TProperties) => {
    return analyticsContext.analytics.track(eventName, properties);
  };
}

```

I need access to the `Callback` since importing from `import { Callback } from '@segment/analytics-next/dist/pkg/core/callback';` will make it fail, see #311

**Comment by pooyaj** [comment]
@yordis Can you define the type in your own codebase? `Callback` type is fairly simple (`(ctx: Context) => Promise<unknown> | unknown`) so may not worth exposing on our library side

**Comment by yordis** [comment]
@pooyaj although, it's quite simple, I would appreciate it if I don't have to honestly. Such type belongs to the public API (`track` func). So it is fair to expose such types if they belong to the public API.

Being said, for the time being, I am gonna close it for now.

**Comment by yordis** [comment]
Actually, let me reopen this because even if I don't want access to the callback the existing type is hard to work with.

![Screen Shot 2022-03-10 at 12 56 42 AM](https://user-images.githubusercontent.com/4237280/157598732-fb0513fd-74b0-486a-959e-d4624db4eab9.png)

I feel that wanting a more strict typing is a decent ask. Notice that even assigning `object` doesn't make the typespec happy.

Maybe don't expose `Callback` but allow us to lock the typespec is a fair ask since it will help our applications to enforce correctness at the type system level.
