### ISSUE TITLE
Regression in functionality of `trackLink` between v1 and v2

### ISSUE THREAD

**Issue by mmoulton** [segmentio/analytics-next#365]
While attempting to upgrade to using the new Segment Analytics 2.0 library I ran into a change in behavior in how the `trackLink` helper works.

For our use case we are attaching the `trackLink` method to `DIV` elements to track interactions within client side features that are not actually anchor elements and do not contain a `href` property we ever intend to direct the browser to.

This functionality is fully supported in the classic Analytics.js library as it would simply initiate a `track` call, then wait 300ms only if it found a `href` property on the direct element you called the original `trackLink` method on. See: https://github.com/segmentio/analytics.js-core/blob/da691296b4a184271f85677962fc19741988c0f3/lib/analytics.ts#L484

This functionality has significantly changed in the 2.0 library. It seems the new behavior is to take the element passed into `trackLink` and find ANY descendent `A` element that has an `href` property and treat that link as if the user actually clicked on it. Needless to say, this can lead to significant unintended consequences. See: https://github.com/segmentio/analytics-next/blob/2691b8808e3e33f97ca7a79e041c228f6fe3a67d/src/core/auto-track.ts#L75

So my question is, is this new change in functionality actually intended?

If so, I feel this is a significant regression and should be called out in the migration guide: https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2/

**Comment by arielsilvestri** [comment]
Hello @mmoulton, and thank you for flagging this! The migration guide has been updated with [a section on this change](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2/#using-tracklink-on-elements-that-are-not-links).
