### ISSUE TITLE
context traits behave differently to mobile Analytics SDKs

### ISSUE THREAD

**Issue by jparksecurity** [segmentio/analytics-next#379]
The context doesn't have a trait when a user is signed in. Is it intended or simply a missing feature?

The same issue is documented in the old repo: https://github.com/segmentio/analytics.js/issues/656

**Comment by jparksecurity** [comment]
@pooyaj Thank you for the response! I'd look into the reference.

**Comment by alexsullivan-pi** [comment]
@pooyaj I'm sorry to reopen this issue, but I'm very confused about how traits work on the web now. From my testing, it appears that traits show up only when you supply them for each tracking call. But if that's the case, then what is the value of providing traits for the `identify` call? And what's the value of traits in general? I think I'm missing something but I'm not getting much clarity from the referenced article.
