### ISSUE TITLE
Can we use plugins with AnalyticsNode?

### ISSUE THREAD

**Issue by kylegwalsh** [segmentio/analytics-next#380]
I haven't seen much discussion about the AnalyticsNode portion of the repo, but it seems to support sending Analytics events from a server.

Is there any way to use the same plugins functionality that is used by AnalyticsBrowser? If not, is there any way to add middleware to AnalyticsNode?

**Comment by kylegwalsh** [comment]
@chrisradek 

Thank you for the quick reply and the thorough response!

Should we also use identifies as normal with AnalyticsNode? I believe the old analytics-node library required a userID to be sent top-level in track events in order to associate events with a user.

**Comment by chrisradek** [comment]
`AnalyticsNode` won't automatically assign the userID to all track events, so you'll still need to set that yourself to associate events with a user.

**Comment by kylegwalsh** [comment]
@chrisradek 

Where would that be set? As a top-level property? Or somewhere in the options of a track event? I see the the `anonymousId` property inside of the "Options" type, but don't see an actual userId in there.

**Comment by chrisradek** [comment]
@kylegwalsh Sorry it looks like I was mistaken, you actually _can_ call `identify` and it will populate the track calls. The risk there is that if you have multiple `identify` and `track` calls being invoked concurrently then a track call could have an unexpected userId associated with it. (This is more common when writing a service in node, if you have an application with a single user then it would be fine to rely on that behavior).

It's not currently typed correctly, but you can pass the `userId` alongside the `anonymousId` as part of the track `Options`. We'll ned to update the typings on our end but it will work currently.

**Comment by kylegwalsh** [comment]
@chrisradek 

Perfect, the latter method is actually more convenient for me anyway! I will make sure to tag the userId in the options whenever I trigger a track call.

Thanks for your help.
