### ISSUE TITLE
Disabling tracking in development mode

### ISSUE THREAD

**Issue by steverob** [segmentio/analytics-next#383]
In the development environment, I'd like to keep tracking disabled. I'm trying to skip `analytics.load()` in dev mode. But then this is breaking `analyics.track()` calls that pass a callback to fire after tracking. The other option I see is to skip including `analytics.js` altogether in dev but then that would mean I'm checking if `analytics` is defined everywhere its being used. Another option is to create a mock implementation of `analytics.js` that does nothing but is API compatible with the library.

Is there a better way to transparently run this in development mode without breaking the application or having to write a lot of conditionals? Or should I just setup a free Segment account and link development mode to that account?

Just looking to see if there is a clean recommended approach for this use case.

**Comment by chrisradek** [comment]
@steverob 
Are you including analytics.js on your page by using the JS snippet, or are you bundling it into your app?

With the snippet, if you don't call `analytics.load()` then any calls you make (e.g. `analytics.track()`) will be pushed onto the global `analytics` object. If you never call `load()`, then any analytics calls you make shouldn't fail - they just go into the analytics array waiting for `load()` to be called.

What are you seeing happen when you say `track` calls invoked with a callback are breaking if you try to skip calling `analytics.load()`?

**Comment by steverob** [comment]
@chrisradek so the tracking code I'm using is the JS snippet from Segment dash plus conditionals to load if enabled. Write key ENV var is not set in dev mode.

```
<script>
  !function(){
    var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on","addSourceMiddleware","addIntegrationMiddleware","setAnonymousId","addDestinationMiddleware"];analytics.factory=function(e){return function(){var t=Array.prototype.slice.call(arguments);t.unshift(e);analytics.push(t);return analytics}};for(var e=0;e<analytics.methods.length;e++){var key=analytics.methods[e];analytics[key]=analytics.factory(key)}analytics.load=function(key,e){var t=document.createElement("script");t.type="text/javascript";t.async=!0;t.src="https://cdn.segment.com/analytics.js/v1/" + key + "/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n);analytics._loadOptions=e};analytics._writeKey="<%= ENV['TELEMETRY_FRONTEND_WRITE_KEY'] %>";analytics.SNIPPET_VERSION="4.13.2";

    <% if ENV['ENABLE_TELEMETRY'].present? && current_user.present? %>
      analytics.load("<%= ENV['TELEMETRY_FRONTEND_WRITE_KEY'] %>");
      analytics.page();
      analytics.identify("<%= current_user.id %>", JSON.parse('<%= raw j(telemetry_user_properties(current_user).to_json) %>'));
    <% end %>
  }}();
</script>

```

As you can see I'm skipping over `analytics.load()` and then I'm doing the following to do the tracking: `analytics.track('event_name', {key: 'val'}, () => {console.log("callback")})` and I'm seeing that the callback is not being called.

**Comment by chrisradek** [comment]
Right, if analytics.load() is never called, then even though calling `analytics.track` won't throw an error, it also won't actually do anything useful. If you don't need the callbacks to be triggered in dev mode then this should be the equivalent of having an 'API compatible' mock of analytics.js that doesn't actually do anything.

Right now when you call `load()` we make a network call to the CDN to retrieve your settings, so if you don't provide a writeKey that will fail and throw an error. We're working on allowing you to pass your own settings so that you don't have to hit our CDN. Once that piece is done then you could pass your own settings in dev mode that also disables sending events to segment to effectively turn off tracking.

**Comment by steverob** [comment]
Just so I’m clear, you’re saying if I don’t call `analytics.load()` then the callback passed to `analytics.track` would be called?

Regards
Steve Robinson

**Comment by chrisradek** [comment]
> Just so I’m clear, you’re saying if I don’t call `analytics.load()` then the callback passed to `analytics.track` would be called?

The opposite actually. If you don't call `analytics.load()`, then the callback won't be invoked either. The analytics object will still have all the public functions and allow you to call them, but they won't actually execute until `load()` is called.

**Comment by steverob** [comment]
@chrisradek okay. So in order for the callbacks to work, Segment needs to be loaded with a valid key. Is that correct?

So in development mode, if I want to add some behavior in an `analytics.track` callback, then the options for me are:
1. Setup a dev Segment account and use those credentials in dev mode
2. Create an API compatible mock that would be capable of calling callbacks

Is this a correct understanding? thanks! :)
