### ISSUE TITLE
Buffer calls while loading script setup

### ISSUE THREAD

**Issue by yordis** [segmentio/analytics-next#390]
Hey peeps,

Following your example about NextJS, we had to start adding optional chaining (`?`) everywhere around the `analytics` object because there is a timing issue calling the analytics stuff.

https://github.com/segmentio/analytics-next/blob/dcaaae4a5d4678c53b6a48b39b2240d578060cc6/src/browser.ts#L74

It is not clear to me how we should create that `window.analytics` beforehand, for example, how Google Analytics does it:

```ts
(function (window, document, tagName, src, scopeName, a, m) {
  
  // this whole thing
  window['GoogleAnalyticsObject'] = scopeName;
  window[scopeName] = window[scopeName] || function () {
    (window[scopeName].q = window[scopeName].q || []).push(arguments)
  }, window[scopeName].l = 1 * new Date();

  a = document.createElement(tagName), m = document.getElementsByTagName(tagName)[0];
  a.async = 1;
  a.src = src;
  m.parentNode.insertBefore(a, m)

})(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
```

Would be amazing to add some example about it in terms of how to setup such object to avoid timing issues.

----

<details>
<summary>As I was creating the ticket I realized you do the buffering already leaving extra context regardless</summary>
For example:

```ts
export function useIdentifyAnalytics() {
  const analyticsContext = useSegmentAnalyticsContext();
  return (userId: string, traits: any) => {
    // TODO: Remove `?` from the call.
    // We need to find a way to wait for the analytics to be loaded first. This is a temporary fix. The downside of that
    // is that forcing the user to wait for a spinner or something like for analytics to load is not ideal.
    // Ideally, the 3rd party dependency should buffer the calls and only send them when the analytics is loaded,
    // instead us doing all that logic in our app.
    return analyticsContext.analytics?.identify(userId, traits);
  };
```

When this hook (or any other ones that we have) triggers, sometimes the script still loading, so there is no object available yet. So there is a timing issue.

Forcing some spinner in our app is less than ideal since it will impact the user experience drastically in an era where we can't afford more than 500ms to 1sec for user attention.

</details>

**Comment by yordis** [comment]
> For example, you want to be able to call analytics.track before the library is finished loading?

Yes!

**Comment by yordis** [comment]
Also @chrisradek we just found an issue where the AdBlockers are blocking Segment, therefore, loading the script failed, therefore, we had an undefined object

```ts
import { Analytics, AnalyticsBrowser } from '@segment/analytics-next';
import * as React from 'react';

export type UseSegmentAnalyticsProps = {
  writeKey?: string;
};

export function useSegmentAnalytics(props: UseSegmentAnalyticsProps) {
  const [analytics, setAnalytics] = React.useState<Analytics | undefined>(undefined);

  React.useEffect(() => {
    if (!props.writeKey) {
      return;
    }

    async function loadAnalytics() {
      const [response] = await AnalyticsBrowser.load({ writeKey: props.writeKey });
      setAnalytics(response);
    }

    loadAnalytics();
  }, [props.writeKey]);

  return {
    isReady: !!analytics,
    analytics: analytics,
  };
}
```

What would be the ideal fallback? Both, the original problem and this problem belong to the same bucket: what happens when analytics hasn't loaded?

Except that they would have two different outcomes I am guessing.

Buffer waiting for the script isn't a problem, but if the script never loaded, then you will keep filling up the memory.

So handling the error side is critical.

Unless I am missing something.

**Comment by yordis** [comment]
Also, reasons why I created https://github.com/segmentio/analytics-next/issues/310 as well.

I think the integrations with React query could be simpler than it is today, hiding all these issues. More than happy to port the code eventually.

**Comment by chrisradek** [comment]
@yordis Let me first address the buffering question.
Here's an update I made to the nextjs example that will use a modified version of the analytics.js snippet that's called in a `useEffect` hook:
https://github.com/segmentio/analytics-next/compare/example-buffering-nextjs

<details>
<summary>Snippet:</summary>

```ts
function analyticsSnippet(): Analytics | undefined {
  if (typeof window === 'undefined') {
    return
  }
  const analytics: any = window.analytics || []
  window.analytics = analytics
  if (!analytics.initialize) {
    if (analytics.invoked) {
      return analytics
    } else {
      analytics.invoked = !0
      analytics.methods = [
        'trackSubmit',
        'trackClick',
        'trackLink',
        'trackForm',
        'pageview',
        'identify',
        'reset',
        'group',
        'track',
        'ready',
        'alias',
        'debug',
        'page',
        'once',
        'off',
        'on',
        'addSourceMiddleware',
        'addIntegrationMiddleware',
        'setAnonymousId',
        'addDestinationMiddleware',
      ]
      analytics.factory = function (e) {
        return function () {
          var t = Array.prototype.slice.call(arguments)
          t.unshift(e)
          analytics.push(t)
          return analytics
        }
      }
      for (var e = 0; e < analytics.methods.length; e++) {
        var key = analytics.methods[e]
        analytics[key] = analytics.factory(key)
      }
    }
  }

  return analytics
}
```
__useEffect__:
```ts
useEffect(() => {
  setAnalytics(analyticsSnippet())
}, [])
```
</details>

Note that I had to get rid of the `ctx.flush()` calls because the buffered versions of the API all return `undefined`. However, it wasn't necessary to call `ctx.flush()` in the example anyway.

Now with regards to adblockers - do you know if they blocked the call to get `/settings` from the segment CDN, or if it was a specific destination that was blocked?

**Comment by yordis** [comment]
@chrisradek this is the only thing I have in hand

![Screen Shot 2022-03-11 at 2 29 24 PM](https://user-images.githubusercontent.com/4237280/157939023-3342afd5-a51e-4db1-a26f-0307bd416912.png)

**Comment by chrisradek** [comment]
That looks like getting the source settings is getting blocked. Just to confirm, `AnalyticsBrowser.load()` is throwing an error when segment is blocked?

So there are a couple options to handle the ad-blocker case.
1. [Set up a custom domain proxy](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/custom-proxy/) so it appears that analytics.js is being loaded from your own domain.
2. Update the analytics.js snippet so that you can toggle buffering off. This would be for the case where you know AnalyticsBrowser has failed to load and you just want to make sure you aren't causing memory usage to increase.

I'd be happy to include the 2nd option in my example above if that'd be helpful.

**Comment by yordis** [comment]
> Here's an update I made to the nextjs example that will use a modified version of the analytics.js snippet that's called in a useEffect hook:

I have a suggestion here, move the code from the `useEffect` to the callback of `useState` of the analytics instead.

Do you mind tagging me once you create the PR?

**Comment by yordis** [comment]
> That looks like getting the source settings is getting blocked. Just to confirm, AnalyticsBrowser.load() is throwing an error when segment is blocked?

Probably, the reason I say that is because I didn't handle the error case (reasons why I created the ticket here since they are edge cases that I didn't want to mess it up further)

Here is the full setup so far

```ts
import { Analytics } from '@segment/analytics-next';

declare global {
  interface Window {
    analytics: Analytics;
  }
}

import { Analytics, AnalyticsBrowser } from '@segment/analytics-next';
import * as React from 'react';

export type UseSegmentAnalyticsProps = {
  writeKey?: string;
};

export function useSegmentAnalytics(props: UseSegmentAnalyticsProps) {
  const [analytics, setAnalytics] = React.useState<Analytics | undefined>(analyticsSnippet);

  React.useEffect(() => {
    if (!props.writeKey) {
      return;
    }

    async function loadAnalytics() {
      const [response] = await AnalyticsBrowser.load({ writeKey: props.writeKey });
      setAnalytics(response);
    }

    loadAnalytics();
  }, [props.writeKey]);

  return {
    isReady: !!analytics,
    analytics: analytics,
  };
}

function analyticsSnippet(): Analytics | undefined {
  if (typeof window === 'undefined') {
    return;
  }

  const analytics: any = window.analytics || [];
  window.analytics = analytics;
  if (!analytics.initialize) {
    if (analytics.invoked) {
      return analytics;
    } else {
      analytics.invoked = !0;
      analytics.methods = [
        'trackSubmit',
        'trackClick',
        'trackLink',
        'trackForm',
        'pageview',
        'identify',
        'reset',
        'group',
        'track',
        'ready',
        'alias',
        'debug',
        'page',
        'once',
        'off',
        'on',
        'addSourceMiddleware',
        'addIntegrationMiddleware',
        'setAnonymousId',
        'addDestinationMiddleware',
      ];
      analytics.factory = function (e) {
        return function () {
          var t = Array.prototype.slice.call(arguments);
          t.unshift(e);
          analytics.push(t);
          return analytics;
        };
      };
      for (var e = 0; e < analytics.methods.length; e++) {
        var key = analytics.methods[e];
        analytics[key] = analytics.factory(key);
      }
    }
  }

  return analytics;
}
```

**Comment by yordis** [comment]
btw related to this, https://github.com/segmentio/analytics-next/issues/310 since the intention is to remove these setups for React land even futher.

**Comment by yordis** [comment]
P.S: I changed a bit the snippet, will leave some comments in the PR

**Comment by yordis** [comment]
Before I forget,

The code-snippet is definitely optimized for most browsers out there, but they are an easier way to accomplish the same task, and even potentially save bytecode since you don't need to hardcore a list of strings, instead, use `Proxy` among other things.

**Recommendation:**

Have multiple versions of the code-snippet, one of the versions could take advantage of the latest version of JS and let the transpiler optimize for older ones based on the app configuration.

**Comment by keegan-lillo** [comment]
Thanks @yordis for the snippet. I've adapted it a bit to work outside React:

```ts
import { Analytics } from '@segment/analytics-next'

declare global {
  interface Window {
    analytics: AnalyticsBuffered | Analytics
  }
}
```

```ts
import { Analytics, AnalyticsBrowser } from '@segment/analytics-next'

// Borrowed from https://github.com/ts-essentials/ts-essentials
type ElementOf<T extends readonly any[]> = T extends ReadonlyArray<infer ET> ? ET : never

type StubbedMethodName = ElementOf<typeof analyticsStubbedMethods>

type AnalyticsStubbedMethods = {
  [K in StubbedMethodName]: (...args: Parameters<Analytics[K]>) => void
}

interface AnalyticsBuffered extends Array<[keyof AnalyticsStubbedMethods, ...any]>, AnalyticsStubbedMethods {
  /** Flag to tell analytics to stop adding things to the buffer in the event
   * that the library failed to load. */
  _loadFailed?: boolean
  /** Flag to tell if we have initialized the buffered version of Analytics */
  _invoked?: boolean
}

const analyticsStubbedMethods = [
  'addDestinationMiddleware',
  'addIntegrationMiddleware',
  'addSourceMiddleware',
  'alias',
  'debug',
  'group',
  'identify',
  'off',
  'on',
  'once',
  'page',
  'pageview',
  'ready',
  'reset',
  'setAnonymousId',
  'track',
  'trackClick',
  'trackForm',
  'trackLink',
  'trackSubmit'
] as const

/**
 * Factory function to generate a queued version of the {Analytics} class.
 * This allows us to dispatch and track events before the analytics JS has
 * finished downloading from the CDN.
 * @see https://github.com/segmentio/analytics-next/issues/390
 */
function setupAnalytics(): AnalyticsBuffered | Analytics {
  // Stub out window if we are in SSR land
  const _window = typeof window !== 'undefined' ? window : ({} as Window)

  const analytics = _window.analytics ?? []
  _window.analytics = analytics

  // This is how we tell if we have the real Analytics class after it's loaded
  if ('initialize' in analytics) {
    return analytics
  }

  if (analytics._invoked === true) {
    return analytics
  }

  analytics._loadFailed = false
  analytics._invoked = true

  const factory = (methodName: StubbedMethodName) => (...args: any[]) => {
    if (analytics._loadFailed !== true) {
      analytics.push([methodName, ...args])
    }
    return analytics
  }

  for (const methodName of analyticsStubbedMethods) {
    analytics[methodName] = factory(methodName)
  }

  return analytics
}

/**
 * Class that wraps the Segment JS node package that handles queuing tracking
 * calls before the library has finished loading from the CDN.
 */
class Segment {
  private _analytics = setupAnalytics()

  get analytics(): AnalyticsBuffered | Analytics {
    return this._analytics
  }

  load(...args: Parameters<typeof AnalyticsBrowser.load>): void {
    AnalyticsBrowser.load(...args)
      .then(([response]) => {
        this._analytics = response
      })
      .catch(error => {
        console.error('Segment Analytics Load Failed', error)

        // if we failed to load, then we need to tell the buffer to stop
        // appending things to it, otherwise this will leak memory.
        if (!('initialize' in this._analytics)) {
          this._analytics._loadFailed = true
        }
      })
  }
}

export default new Segment()
```

**Comment by silesky** [comment]
@yordis added in https://github.com/segmentio/analytics-next/pull/436/files

**Comment by silesky** [comment]
Released in https://github.com/segmentio/analytics-next/releases/tag/v1.38.0

**Comment by silesky** [comment]
> Thanks @yordis for the snippet. I've adapted it a bit to work outside React:
> 
> ```ts
> import { Analytics } from '@segment/analytics-next'
> 
> declare global {
>   interface Window {
>     analytics: AnalyticsBuffered | Analytics
>   }
> }
> ```
> 
>  ```ts
> import { Analytics, AnalyticsBrowser } from '@segment/analytics-next'
> 
> // Borrowed from https://github.com/ts-essentials/ts-essentials
> type ElementOf<T extends readonly any[]> = T extends ReadonlyArray<infer ET> ? ET : never
> 
> type StubbedMethodName = ElementOf<typeof analyticsStubbedMethods>
> 
> type AnalyticsStubbedMethods = {
>   [K in StubbedMethodName]: (...args: Parameters<Analytics[K]>) => void
> }
> 
> interface AnalyticsBuffered extends Array<[keyof AnalyticsStubbedMethods, ...any]>, AnalyticsStubbedMethods {
>   /** Flag to tell analytics to stop adding things to the buffer in the event
>    * that the library failed to load. */
>   _loadFailed?: boolean
>   /** Flag to tell if we have initialized the buffered version of Analytics */
>   _invoked?: boolean
> }
> 
> const analyticsStubbedMethods = [
>   'addDestinationMiddleware',
>   'addIntegrationMiddleware',
>   'addSourceMiddleware',
>   'alias',
>   'debug',
>   'group',
>   'identify',
>   'off',
>   'on',
>   'once',
>   'page',
>   'pageview',
>   'ready',
>   'reset',
>   'setAnonymousId',
>   'track',
>   'trackClick',
>   'trackForm',
>   'trackLink',
>   'trackSubmit'
> ] as const
> 
> /**
>  * Factory function to generate a queued version of the {Analytics} class.
>  * This allows us to dispatch and track events before the analytics JS has
>  * finished downloading from the CDN.
>  * @see https://github.com/segmentio/analytics-next/issues/390
>  */
> function setupAnalytics(): AnalyticsBuffered | Analytics {
>   // Stub out window if we are in SSR land
>   const _window = typeof window !== 'undefined' ? window : ({} as Window)
> 
>   const analytics = _window.analytics ?? []
>   _window.analytics = analytics
> 
>   // This is how we tell if we have the real Analytics class after it's loaded
>   if ('initialize' in analytics) {
>     return analytics
>   }
> 
>   if (analytics._invoked === true) {
>     return analytics
>   }
> 
>   analytics._loadFailed = false
>   analytics._invoked = true
> 
>   const factory = (methodName: StubbedMethodName) => (...args: any[]) => {
>     if (analytics._loadFailed !== true) {
>       analytics.push([methodName, ...args])
>     }
>     return analytics
>   }
> 
>   for (const methodName of analyticsStubbedMethods) {
>     analytics[methodName] = factory(methodName)
>   }
> 
>   return analytics
> }
> 
> /**
>  * Class that wraps the Segment JS node package that handles queuing tracking
>  * calls before the library has finished loading from the CDN.
>  */
> class Segment {
>   private _analytics = setupAnalytics()
> 
>   get analytics(): AnalyticsBuffered | Analytics {
>     return this._analytics
>   }
> 
>   load(...args: Parameters<typeof AnalyticsBrowser.load>): void {
>     AnalyticsBrowser.load(...args)
>       .then(([response]) => {
>         this._analytics = response
>       })
>       .catch(error => {
>         console.error('Segment Analytics Load Failed', error)
> 
>         // if we failed to load, then we need to tell the buffer to stop
>         // appending things to it, otherwise this will leak memory.
>         if ('_loadFailed' in this._analytics) {
>           this._analytics._loadFailed = true
>         }
>       })
>   }
> }
> 
> export default new Segment()
> ```

@yordis @keegan-lillo  -- since we have supported buffering analytics for over a year, we are dropping support for reading from the window.analytics version if you're using npm.
