### ISSUE TITLE
Make protocol configurable

### ISSUE THREAD

**Issue by livthomas** [segmentio/analytics-next#393]
We use our backend as a proxy to Segment API in order to bypass ad-blockers. But we are unable to test it in local dev environment on our machines where HTTP is used instead of HTTPS.

It looks like HTTPS protocol is hardcoded [here](https://github.com/segmentio/analytics-next/blob/7c63868477ede9272ac9c072931110fe37f0f721/src/plugins/segmentio/index.ts#L58). Can you create a new settings property which specifies protocol and defaults to `https`?

I've already asked for this in https://github.com/segmentio/analytics.js-integrations/issues/559 and there hasn't been any response.

**Comment by arielsilvestri** [comment]
Hey @livthomas, you should now be able to do the following in your load configuration to achieve this:

```javascript
analytics.load('writeKey', {
  integrations: {
    "Segment.io": {
     // Other options...
      protocol: "http"
    }
  }
);
```
