### ISSUE TITLE
Using AnalyticsNode causes node process to hang

### ISSUE THREAD

**Issue by chrismeyers** [segmentio/analytics-next#402]
Hello, I'm currently working on a library that wraps this library to support both Node.js and React (as well as providing some custom validation logic).  As I've been working on the Node.js side, I noticed that running code similar to the sample script in https://github.com/segmentio/analytics-next/pull/352 causes the node process to hang.  I have two questions:
1. Is it intended for the node process to keep running after calling `AnalyticsNode.load`?  If so, is there a way to gracefully stop the process?
2. Is this the best library to use for integrating Segment into backend Node.js applications?  I saw that there's https://github.com/segmentio/analytics-node, but using the same library for both frontend and backend would simplify the maintenance of our wrapper library.

Any help would be appreciated, thank you!

**Comment by chrisradek** [comment]
@chrismeyers Thanks for logging this issue!

 > Is it intended for the node process to keep running after calling AnalyticsNode.load? If so, is there a way to gracefully stop the process?

That's not the intention. It looks like we have a bug in our flushing logic that keeps a setTimeout running - this works fine in the browser but in node.js it's keeping the process open. We'll need to fix that.

> Is this the best library to use for integrating Segment into backend Node.js applications?

We want to make `AnalyticsNode` from this library on par with the `analytics-node` package, but we have not yet fully ported all the tests and behavior over to be able to fully recommend switching over. We've been discussing when to tackle this - potentially in the next quarter.

**Comment by chrismeyers** [comment]
Hey @chrisradek, thanks for the quick response!

Regarding the setTimeout bug, I just wanted to make sure I wasn't going crazy 😄 

The current functionality of `AnalyticsNode` fits the needs of our internal wrapper library, so any additional improvements moving forward would be great!
