### ISSUE TITLE
trackLink and trackForm don't take options

### ISSUE THREAD

**Issue by nmackey** [segmentio/analytics-next#415]
Was wondering why `trackLink` and `trackForm` don't allow an options object to be passed.  I would like to use these functions but I can't anonymize the IP address of my users if I can't pass in options to these functions.

https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/identity/#anonymizing-ip

**Comment by chrisradek** [comment]
@nmackey Thanks for logging this issue! I don't see a reason not to allow passing options to these methods - it seems like a reasonable thing to support!

In case you're currently blocked, a workaround is to write a plugin to anonymize the IP, here's a quick example that will anonymize the ip for every event made:
```js
function anonymizeIp(ctx) {
  ctx.event.context.ip = '0.0.0.0';
  return ctx;
}

const noIpPlugin = {
  name: 'No IP',
  type: 'before',
  version: '1.0.0',
  isLoaded: () => true,
  load: () => Promise.resolve(),

  track: anonymizeIp,
  identify: anonymizeIp,
  page: anonymizeIp,
  alias: anonymizeIp,
  group: anonymizeIp
}
```

If you're using the JS snippet, the easiest way to use this would be to call `analytics.register(noIpPlugin)` right after your snippet - in this case you'd also want to add `"register"` to the `analytics.methods` array of the snippet.

If you're using `analytics-next` in an app where you bundle it yourself then you can add it when you call load:
```js
AnalyticsBrowser.load({ writeKey: 'writeKey', plugins: [noIpPlugin] })
```

**Comment by danieljackins** [comment]
Fixed with https://github.com/segmentio/analytics-next/pull/417

**Comment by nmackey** [comment]
Thanks for the fix and the anonymizeIp plugin/function 🔥
