### ISSUE TITLE
Support for load options?

### ISSUE THREAD

**Issue by sufyanadam** [segmentio/analytics-next#419]
Does this package support load options? https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#load-options

I was trying it out and it doesn't seem to currently. Do we have to use the snippet version instead if we need this capability?

**Comment by chrisradek** [comment]
@sufyanadam 
`loadOptions` works both with the snippet or if you're using the package directly in your project. What issue are you seeing?

**Comment by sufyanadam** [comment]
Thanks for the response. On further investigation, it was necessary to set `window.intercomSettings` to hide the intercom launcher in addition to setting the integration value for the load options for intercom to false. I will close this. Thank you for confirming that support for load options exists.
