### ISSUE TITLE
create-react-app Shows warnings in console.

### ISSUE THREAD

**Issue by Nicktho** [segmentio/analytics-next#420]
Hello!

After installing and using analytics-next in a create-react-app we're getting quite a few warnings in the console when running in development, they are all similar to the following:

![image](https://user-images.githubusercontent.com/8622243/161896017-b4955d13-e499-4e41-b6b4-50200c8a9dc2.png)

**Comment by chrisradek** [comment]
@Nicktho Thanks for logging this issue! Looks like this shouldn't prevent your builds from running but does indicate that the source-maps for `@segment/facade` are not working. This is something we should be able to take care of.

**Comment by chrisradek** [comment]
PR created to fix this here: https://github.com/segmentio/facade/pull/174

**Comment by chrisradek** [comment]
`@segment/analytics-next` version 1.35.1 has been released and includes a fix for this issue. Let us know if you still encounter sourcemap problems after updating!

**Comment by chrisradek** [comment]
@devaublanc Thanks for letting us know - looks like when we published the new `@segment/analytics-core` package we didn't publish the sources for the source maps.

**Comment by silesky** [comment]
@chrisradek should be fixed by https://github.com/segmentio/analytics-next/pull/547

**Comment by silesky** [comment]
Fixed in 1.42.0
