### ISSUE TITLE
🚨 Circular dependencies

### ISSUE THREAD

**Issue by xesjkeee** [segmentio/analytics-next#429]
Hey guys, I've found 9 (🚨) circular dependencies in your project

There are red files those have circular dependencies, you can check by yourself using [Madge](https://github.com/pahen/madge)

```bash
❯ madge --extensions ts,vue --image ./graph.svg --exclude '(spec)\.ts$' ./src
```

_(click to open in new tab)_

![graph](https://user-images.githubusercontent.com/17751886/162786475-7be011b9-3599-46e2-96a6-3480d0878a51.svg)

**Comment by cjmosure** [comment]
Related, I am getting a circular dependency warning when bundling analytics-next with rollup:

```
(!) Circular dependency
../../node_modules/@segment/analytics-next/dist/pkg/analytics.js -> ../../node_modules/@segment/analytics-next/dist/pkg/browser.js -> ../../node_modules/@segment/analytics-next/dist/pkg/analytics.js
```
