### ISSUE TITLE
Update integrations object after load ? 

### ISSUE THREAD

**Issue by chambo-e** [segmentio/analytics-next#434]
Hello, 

Just wondering if it would be possible to set the integrations passed onto le load function at runtime ? 

```ts
const analytics = await AnalyticsBrowser.load({}, { integrations: { All: false, RandomIntegration: false } })
analytics.setIntegrations({ All: false, RandomIntegration: true })
```

I'm currently integrating a kind of consent manager and I'd like to enable/disable integrations without reloading the page, this would allow changing integration flow at runtime without the need to
First I intended to do this with a plugin but you seem to block enabling an integration afterwards https://github.com/segmentio/analytics-next/blob/2490333f3c32b922887fdb043ca3101d4c5e25df/src/core/context/index.ts#L104

Thanks in advance

**Comment by pooyaj** [comment]
Sorry for the delay. Currently it is not possible to modify the enabled integrations during the runtime. Although, you can write a plugin that modifies the `this._event.integrations` object to selectively send events to a particular destination.
