### ISSUE TITLE
"ChunkLoadError: Loading chunk ajs-destination failed." on Safari browser 

### ISSUE THREAD

**Issue by beqramo** [segmentio/analytics-next#435]
Hi,

the library's codes aren't loading on the safari browser, on chrome it works perfectly.
I don't know if there is any difference but it is a browser extension.

I tried  AnalyticsNode package but after that it says this:
`AnalyticsNode is not available in browsers.`

<img width="979" alt="image" src="https://user-images.githubusercontent.com/40486471/165559504-fe70204c-a5ff-4c0d-9896-b22860d5a977.png">

```json
 "dependencies": {
...
    "@segment/analytics-next": "^1.35.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
  },
 "devDependencies": {
...
    "typescript": "^4.1.5",
    "webpack": "^5.70.0",
    "webpack-cli": "^4.9.2",
    "webpack-dev-server": "^4.7.4"
  }
```

**Comment by chrisradek** [comment]
@beqramo Can you share a minimal repro setup? I've only worked briefly with chrome extensions and haven't got a working safari extension yet.

When I've used webpack for a chrome extension, I see some additional files such as `ajs-destination.js` after building -> do you have something like this in your safari extension project?

**Comment by beqramo** [comment]
thanks for the comment, I think that is the problem, I just realised that there is no such file. will try to fix it and will get back to you if it will work.

**Comment by pooyaj** [comment]
Closing, please feel free to re-open if still an issue
