### ISSUE TITLE
Track events are setting undefined on url, referrer, and search properties

### ISSUE THREAD

**Issue by kamui** [segmentio/analytics-next#451]
We're using `analytics-next` as an npm module, calling `load` and then a basic `analytics.track` event without any options or overrides. The only plugin we have is `scrubPii` enabled.

While `analytics.page` events have these properties all set properly, track events seem to set these as `undefined`, even though the `context.page` object does seem to have these values, the properties come in as empty. I would expect them to come in just like the `analytics.track` event, fully populated.

The call looks like this:

```
analytics.track("Header Link Clicked", { item: "Treatments" })
```

In Segment debugger:

```
  "properties": {
    "item": "Treatments",
    "referrer": "undefined",
    "search": "undefined",
    "url": "undefined"
  },
```

![image](https://user-images.githubusercontent.com/2255/167029982-453183fa-fada-412a-88af-587b161336b3.png)

**Comment by chrisradek** [comment]
@kamui 
Thanks for creating this issue! For your track calls, I would have expected the `referrer`, `search`, and `url` properties to not exist at all in your `properties` object, just in `context.page`. `properties` should only contain what you've supplied to your `track` call.

I'm not familiar with the scrubPii plugin - is this something you can share?

**Comment by kamui** [comment]
Good question, it's custom middleware and upon further investigation, it was responsible for this bug, so I'm closing this. Sorry for not checking this plugin first and thanks!
