### ISSUE TITLE
Error in Documentation

### ISSUE THREAD

**Issue by ricardojr** [segmentio/analytics-next#475]
https://github.com/segmentio/analytics-next#-using-as-an-npm-package

Your NPM documentation is wrong. the `load()` method is `asynchronous` and returns a promise. The way the example are written it makes it seem its `synchronous`. 

Also, the fact `load()` is `async` greatly complicates things. Typically client initializations are `synchronous`.

**Comment by ricardojr** [comment]
My mistake. I'm noticing some inconsistencies with my code and your repo. Maybe I am using an old version.

**Comment by silesky** [comment]
@ricardojr, the API gives the user of using it either async or synchronously. AnalyticsBrowser is not a promise, it's actually a thenable.

```ts
const ajs = AnalyticsBrowser.load({ writeKey: 'foo' }) //  returns an instance of AnalyticsBrowser which is a _thenable_
ajs.track("hello world") 

// and this also works!
const [analytics, context] = await ajs
```

**Comment by ricardojr** [comment]
Ok thanks makes sense.
