### ISSUE TITLE
Link to "existing plugins" in README is broken

### ISSUE THREAD

**Issue by dobesv** [segmentio/analytics-next#494]
To reproduce:

1. Go to https://github.com/segmentio/analytics-next
2. Scroll to the bottom
3. Click "existing plugins"

Maybe it's supposed to link to https://github.com/segmentio/analytics-next/tree/master/packages/browser/src/plugins ?

**Comment by silesky** [comment]
Thanks @dobesv. Fixed in https://github.com/segmentio/analytics-next/pull/495/files
