### ISSUE TITLE
How to remove fields from context before sending to segment.io

### ISSUE THREAD

**Issue by eduardoacskimlinks** [segmentio/analytics-next#499]
SDK version
cdn.segment.com/analytics.js/v1/analytics.min.js -> SNIPPET_VERSION 2.0.9

We are using the native code given by the snippet.

```
...
window.analytics.SNIPPET_VERSION = "2.0.9"
window.analytics.load( "API KEY")
window.analytics.page(undefined, undefined, {
    search: null,
    url: null
})
```

We attempt to remove sensitive data from the URL and search parameters on certain pages. However, the data persist in the context, as you can see below.

```
{
  "integrations": {},
  "userId": "XXX",
  "anonymousId": "UUID",
  "type": "page",
  "properties": {
    "path": "/resetpassword",
    "referrer": "",
    "search": null,
    "title": "Hub | Skimlinks",
    "url": null
  },
  "context": {
    "page": {
      "path": "/resetpassword",
      "referrer": "",
      "search": "?email=X",
      "title": "Hub | Skimlinks",
      "url": "http://localhost:8080/resetpassword?email=X"
    },
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36",
    "locale": "en-GB",
    "library": { "name": "analytics.js", "version": "next-1.38.0" },
    "campaign": {}
  },
  "messageId": "ajs-next-version",
  "writeKey": "KEY",
  "sentAt": "2022-06-22T13:11:07.087Z",
  "timestamp": "2022-06-22T13:11:07.087Z",
  "_metadata": {
    "bundled": ["Google Analytics", "KISSmetrics", "Segment.io"],
    "unbundled": [],
    "bundledIds": ["xID", "xID"]
  }
}
```

How can we customise the context data sent? Is any way for us to choose which fields are tracked?

**Comment by pooyaj** [comment]
@eduardoacskimlinks you should be able to use a plugin to do that: 
```javascript
const sanitizePlugin = {
  load() {
    return Promise.resolve()
  },
  isLoaded() {
    return true
  },
  name: 'Sanitize',
  type: 'enrichment',
  page: async (ctx) => {
    ctx.event.properties = {
      ...ctx.event.properties,
      path: 'redacted',
    }
    return ctx
  },
};

analytics.register(sanitizePlugin) 
```


More info on plugins here: https://github.com/segmentio/analytics-next#-plugins

**Comment by eduardoacskimlinks** [comment]
> Hey @eduardoacskimlinks, I double-checked the instructions shared in our [troubleshooting](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/troubleshooting/#can-i-overwrite-the-context-fields) section, and I was able to overwrite the context fields. I took a look at your example and I think you were passing `null` to the properties fields, here's an example of passing null to the context object fields instead:
> 
> ```
> analytics.page('Home', {},{
>     page: {
>       url: null,
>       search: null} 
> });
> ```

Thanks, I am aware of the approach but if you look closely into the request when you apply that approach the context variable remain intact as you see in my first comment. Therefore, this causes to leak sensitive data through the context. I believe @pooyaj is the best one in this case
