### ISSUE TITLE
How do you make all cookies secure?

### ISSUE THREAD

**Issue by mflorenciapereira** [segmentio/analytics-next#550]
Is there an option we can use to force all the cookies used to be secure (cookie flag)? Thanks

**Comment by chrisradek** [comment]
@mflorenciapereira Thanks for opening this issue! Yes there is a way to specify that all cookies should be secure!

Here's a list of all the cookie settings we support:
https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/persistence/#cookie-settings

To set it, you can do something like:
```js
analytics.load('writeKey', {
  cookie: {
    secure: true
  }
});
```

**Comment by t2farrell** [comment]
Does this actually work?  After setting this option, the `analytics` object in the console contains visible properties for cookies that include `secure: true` however, the cookies collection displayed by the browser seem to indicate that they are not, in fact, marked secure?

**Comment by chrisradek** [comment]
@t2farrell 
We discovered the secure setting wasn’t being applied to all cookies and made a fix in https://github.com/segmentio/analytics-next/pull/577

I don’t think this has been released to the CDN hosted version of the sdk but we should be able to release it this week.

**Comment by t2farrell** [comment]
Great, thanks!

**Comment by florencia-pereira-vectorsolutions** [comment]
I had tried and wasn't working but now with the new version we can try again. Thanks!
