### ISSUE TITLE
Recommended strategy for disabling tracking under specific conditions?

### ISSUE THREAD

**Issue by mwisner** [segmentio/analytics-next#558]
Hi, 

First, we're really enjoying all the hard work everyone is putting into this library!

I was wondering if there was a recommended approach to disabling Segment for select users?

We are bundling the SDK with our app, and doing something like:

```
import { AnalyticsBrowser } from '@segment/analytics-next';

const analytics = AnalyticsBrowser.load({
 ....
});

export default analytics;
```

I'm hoping to come up with a way that disables all segment tracking (including MTUs) but doesn't actually break anything. We have a non-trivial amount of bot traffic that can execute javascript (headless chrome) (for example, we have multiple bots that hit every single page of the site) which causes lots of unnecessary data to be sent to Segment. 

I see this issue also, but it looks like the discussion is specifically around the hosted snippet.
https://github.com/segmentio/analytics-next/issues/383

Again thank you so much for this Library, and any recommendations on this issue would be greatly appreciated!

**Comment by silesky** [comment]
Thank you! Would we be interested in something like a configuration variable -- something like 

export const analytics = AnalyticsBrowser.load({
   enabled:  window.ANALYTICS_DISABLED
});

**Comment by mwisner** [comment]
Hi @silesky, that would be perfect for our use case.

**Comment by chrisradek** [comment]
As @silesky alluded to in his example comments, you can also write a plugin that cancels event delivery based on whatever rules you want to set. analytics-next version 1.40.0 fixes an issue that was preventing plugins from cancelling delivery, so you'd need to be using at least that version for this to work.

Here's an example of what that plugin could look like:
```js
export class TogglePlugin {
    constructor({ disableAjs }) {
        this.name = 'Toggle Event Delivery Plugin';
        this.type = 'before'; // Only `before` plugins can prevent event delivery
        this.version = '1.0.0';
        this.ajsDisabled = disableAjs;
    }
    load() {
        return Promise.resolve();
    }
    isLoaded() {
        return true;
    }
    gateKeep(ctx) {
        if (!this.ajsDisabled) {
            return ctx;
        }
        ctx.cancel(new ContextCancelation({
            reason: 'AJS Disabled due to bot',
            retry: false
        }));
    }
    alias(ctx) {
        return this.gateKeep(ctx);
    }
    identify(ctx) {
        return this.gateKeep(ctx);
    }
    group(ctx) {
        return this.gateKeep(ctx);
    }
    page(ctx) {
        return this.gateKeep(ctx);
    }
    track(ctx) {
        return this.gateKeep(ctx);
    }
}
```

Then you'd pass it into `AnalyticsBrowser.load()`:
```js
const analytics = AnalyticsBrowser.load({
  writeKey: 'key',
  plugins: [new TogglePlugin({ disableAjs: true })]
})
```

**Comment by silesky** [comment]
@chrisradek nice!
