### ISSUE TITLE
initialPageview causing duplicate page calls

### ISSUE THREAD

**Issue by plumber-dhaval** [segmentio/analytics-next#566]
when using analytics-next with react if `initialPageview` is true page() fires twice in segment debugger.
```
  const analytics = useMemo(
    () => AnalyticsBrowser.load({ writeKey }, { initialPageview: true }),
    [writeKey],
  );
```

**Comment by pooyaj** [comment]
Hi @plumber-dhaval, I can't reproduce this one using the latest version of the library.
