### ISSUE TITLE
Typescript Type Too Strict/Explicit in Track Method Signature

### ISSUE THREAD

**Issue by joneath** [segmentio/analytics-next#569]
In the `1.42.0` release and continuing in `1.42.1` the type definition for the second property is too strict/explicit and throws the following type error:

```
Argument of type 'Assessment' is not assignable to parameter of type 'EventProperties | Callback'.

analytics?.track('assessment:assigned', assessment)
```

Previously I could pass my own types to the `track` method without a problem. I can force the type to `any` to get around the error but that's a nasty workaround...

**Comment by silesky** [comment]
Hey @joneath. I recommend that you cast the assessment type to a vanilla JS object (e.g. add a toJSON method).

 in 1.42.0, we ended up tightening up the types no longer support passing any arbitrary object to Analytics, as the "object" type ends up allowing arrays and functions, and swallows Callback. 
for the record, The following works: 
```ts
type Assessment = {
  name: string
}
const assessment: Assessment = { name: "foo"}
analytics.track('assessment:assigned', assessment)
```

The following also works: 
```ts
class Assessment {
  foo() {
    return 123
  }
  bar: string = 'sup'
}

const f = new Assessment()

analytics.track("assessment:assigned', {...f})
```

The following *DOES NOT WORK*
```ts
class Assessment {
  foo = () =>  {
    return 123
  }
  bar: string = 'sup'
}

const f = new Assessment()

analytics.track("assessment:assigned', {...f}) // you're passing a function as key -- which we don't allow
```
