### ISSUE TITLE
undefined as JSONValue

### ISSUE THREAD

**Issue by chambo-e** [segmentio/analytics-next#570]
Hello 👋 

Since https://github.com/segmentio/analytics-next/pull/561 we are unable to pass undefined as a value to track/identify calls as JSONValue does not accept undefined values

Meaning this kind of (pseudo) function

```ts
const trackUser = ({ userId, language }: { userId: string, language?: string }) => {
    analytics.track(
      'User',
      {
        userId,
        language,
      })
}
```

Does not work anymore whilst it used to be a valid way to pass optional values.

Filtering undefined values can be a solution but a quite heavy one when JSON.stringify automatically strip undefined values

Could undefined be added back as a possible values to objects ? 

```ts
export type Traits = { [k: string]: JSONValue | undefined }
export type EventProperties = {
  [k: string]: JSONValue | undefined
}
```

Thanks :)

**Comment by silesky** [comment]
Thanks @chambo-e for reporting this. This seems reasonable that we want to allow JSON values, but also allow undefined properties, as we assume that is desirable that they any undefined values are removed on serialization. 

In the meantime, you could fallback on null.
```ts
const trackUser = ({ userId, language }: { userId: string, language?: string }) => {
    analytics.track(
      'User',
      {
        userId,
        language: language ?? null
      })
}
```
