### ISSUE TITLE
Delay initialization

### ISSUE THREAD

**Issue by gajus** [segmentio/analytics-next#571]
Is there a way to delay `AnalyticsBrowser` initialization?

Ideally, we would start `AnalyticsBrowser` in a state that buffers the requests, and when ready to initialize, would replay the events.

Context: We are trying to reduce the number of requests that fire when page is loading.

**Comment by chrisradek** [comment]
@gajus Thanks for opening this issue!

If you call `AnalyticsBrowser.load()` without awaiting it, it will buffer requests until loading is completed (done behind the scenes), then send those events.

Example with buffering:
```js
const analytics = AnalyticsBrowser.load({ writeKey: 'writeKey' })
analytics.page() // This call is buffered until analytics finishes initialization
```

Example without buffering:
```js
const [analytics] = await AnalyticsBrowser.load({ writeKey: 'writeKey' })
analytics.page() // Analytics already finished initialization when we awaited it, so this is not buffered
```

Does this meet the needs for your use-case or do you need more granular control over when initialization occurs? If more granular control is needed, we would like to better understand what issues you're running into when the page is loading.

**Comment by gajus** [comment]
> Does this meet the needs for your use-case or do you need more granular control over when initialization occurs? If more granular control is needed, we would like to better understand what issues you're running into when the page is loading.

It does.

We also pass `cdnSettings` (which appears to be undocumented) to avoid the initial `/settings` request.

Regarding `AnalyticsBrowser.load`, I would strongly suggest having a separate method, like `lazyLoad`, to avoid confusion. It is very unintuitive to overload promise interface.

**Comment by silesky** [comment]
@gajus thank you for the feedback! We'll keep this data point in mind, we will likely end up deprecating the async behavior at some point so it will no longer be a promise, but it's legavy.
