### ISSUE TITLE
Argument of type `Record<string, string>` is not assignable to parameter of type `Traits | Callback | null | undefined`

### ISSUE THREAD

**Issue by zygopleural** [segmentio/analytics-next#575]
**Breaking change introduced** 

I have a breaking change trying to upgrade [1.41.0 -> 1.42.1](https://renovatebot.com/diffs/npm/@segment%2fanalytics-next/1.41.0/1.42.1)

# Expected

I should be able to pass any `Record<string, string | number | JSONValue>` as traits into the `identify` call.

# Actual

I can only only pass `Record<string, JSONValue>`

# Culprit

Looks like here was a breaking change in [@segment/analytics-next@1.42.0](https://github.com/segmentio/analytics-next/releases/tag/%40segment%2Fanalytics-next%401.42.0)

I believe https://github.com/segmentio/analytics-next/pull/561 is the culprit, specifically [these changes](https://github.com/segmentio/analytics-next/pull/561/files#diff-de3038f626aa3daf3759249f0a10fe86c7b9c119867341667d685d7656a643c0R151-R154)

**Comment by silesky** [comment]
@zygopleural I wasn't able to quickly reproduce.

This works:
```ts
const traits: Record<string, string> =  {name: "hello"}
analyics.identify("foo", traits)
```

**Comment by zygopleural** [comment]
```ts
const { id, picture, signInMethod, ...traits } = user
identify(id, traits)
```

I'm seeing

<img width="766" alt="Screenshot 2022-08-10 at 16 41 02" src="https://user-images.githubusercontent.com/31384409/183948629-c6cf3e40-945f-40d4-b188-776a3bb91651.png">

Even if I do
```ts
const t = traits as Traits
```

<img width="765" alt="Screenshot 2022-08-10 at 16 42 33" src="https://user-images.githubusercontent.com/31384409/183948639-d5c09e7a-f41d-41a0-9515-95c6b1871f12.png">

**Comment by silesky** [comment]
@zygopleural  This is an interesting one. Can you create a type and then cast it to that?

```ts
type UserTraits = {
  name: string
  age: string
}
const { id, picture, signInMethod, ...traits } = user
identify(id, traits as UserTraits)
```

**Comment by silesky** [comment]
@zygopleural  be fixed in 1.42.2

**Comment by silesky** [comment]
FYI @zygopleural there is a recently active open issue about this scanario: https://github.com/microsoft/TypeScript/issues/48014

**Comment by zygopleural** [comment]
> FYI @zygopleural there is an open Typescript issue about this scenario / bug: https://github.com/microsoft/TypeScript/issues/48014

Ah nice find!
