### ISSUE TITLE
How to use analytics-next in getServerSideProps Next.js

### ISSUE THREAD

**Issue by ahetawal-p** [segmentio/analytics-next#584]
I am following this example 
https://github.com/segmentio/analytics-next/tree/master/examples/with-next-js
for nextJs integration but it seems to be more client/browser specific.
We do server side authentication and would like to for example: call `identify` when the user first logs in through SSR.

Is there any example which I can use to provide server side analytics and same applies for any api routes.?

Thank you,

**Comment by ahetawal-p** [comment]
Thanks @silesky I think at this time I will stick with client-side `identify` call and I guess same goes for the api routes. 
I was just curious if any SSR support was available for segment.

Thank you again,

**Comment by amosbastian** [comment]
@silesky did you guys move it to another package yet? Or for when is this planned?

**Comment by silesky** [comment]
@amosbastian we haven't publicized it yet, but we've actually just released a beta. https://www.npmjs.com/package/@segment/analytics-node
