### ISSUE TITLE
Support for analytics.load() as effect

### ISSUE THREAD

**Issue by aaronadamsCA** [segmentio/analytics-next#585]
I can't figure out how I could call `analytics.load()` after DOM hydration, without losing any analytics events queued beforehand.

We currently use the snippet, but I want to eliminate this vendored code from our repository.

Based on how the snippet works, this is the kind of approach I was expecting from this library:

```ts
const analytics = useMemo(() => {
  return new AnalyticsBrowser({ writeKey });
}, [writeKey]);

useEffect(() => analytics.load(), [analytics]);
```

Instead it seems I'm expected to synchronously initialize `analytics`, and simply trust that the initialization will somehow not affect our site speed. This does not seem like a good approach.

There doesn't seem to be much in the way of documentation or examples; is there an easy way to do this today, or am I better off just sticking with the snippet for now?

**Comment by silesky** [comment]
The snippet uses this library including its own initialization pattern, there is no functional difference whatsoever from a performance PoV. It is a matter of preference. 

The "synchronous" initialization  has low overhead and is meant to be for convenience -- it simply creates methods that simply queue method calls, which get dispatched them when the library is fully loaded (for example, scripts are loaded in device mode) so you don't lose events that occur before initialization.


Have you actually tested perf? I am doubtful that wrapping our library in a useEffect will add any performance benefits over the example which uses useMemo. You can certainly use useEffect if you don't care about queing, but it's more boilerplate:

  const [analytics, setAnalytics] = useState<Analytics | undefined>(undefined)
  const [writeKey, setWriteKey] = useState('<YOUR_WRITE_KEY>')

  useEffect(() => {
    const loadAnalytics = async () => {
      let [response] = await AnalyticsBrowser.load({ writeKey })
      setAnalytics(response)
    }
    loadAnalytics()
  }, [writeKey])

**Comment by zikaari** [comment]
> We currently use the snippet, but I want to eliminate this vendored code from our repository.

Can you please clarify what code do want to eliminate, _(and what do you wish to replace it with)_? Is it the snippet in the document head or the boilerplate code that you posted?
