### ISSUE TITLE
Service workers

### ISSUE THREAD

**Issue by GarageInc** [segmentio/analytics-next#586]
Is it possible to use it at service workers? There are no 'addEventListener' and window object

**Comment by silesky** [comment]
Hey @GarageInc -- thank you for the inquiry! Service workers are not currently possible, as this library makes use of window to load a user's third-party scripts ("device mode"), and, in some limited places, such as to get query string data or store queued method calls (if you're a snippet user). We will be evaluating the possibility of supporting service worker in the future for a limited feature set in the coming year.
