### ISSUE TITLE
Custom plugins don't run for events queued before segment is fully loaded

### ISSUE THREAD

**Issue by agnieszkaziaja** [segmentio/analytics-next#589]
I've followed the example code to create a plugin that anonymizes IP addresses in events before they get sent to Segment.

Our application is quite complicated and we execute calls to `track()`, `page()` and `load()` before the Segment JS file is fully loaded on our application. 

We've observed that our custom plugin doesn't run for any events that are queued up before Segment is fully loaded. However, after segment is loaded, our plugin does work when calling `analytics.track()`.

It turns out that this simple HTML file reproduces the issue exactly (run it in your browser using `npx http-server` or a similar local web server for static assets):

```
<html>

<body>
    <script>
        // Standard segment snippet from your documentation 
        !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on","addSourceMiddleware","addIntegrationMiddleware","setAnonymousId","addDestinationMiddleware"];analytics.factory=function(e){return function(){var t=Array.prototype.slice.call(arguments);t.unshift(e);analytics.push(t);return analytics}};for(var e=0;e<analytics.methods.length;e++){var key=analytics.methods[e];analytics[key]=analytics.factory(key)}analytics.load=function(key,e){var t=document.createElement("script");t.type="text/javascript";t.async=!0;t.src="https://cdn.segment.com/analytics.js/v1/" + key + "/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n);analytics._loadOptions=e};analytics._writeKey="SEGMENT_KEY";analytics.SNIPPET_VERSION="4.15.2";

        analytics.load("SEGMENT_KEY");
        analytics.page();

        window.analytics.debug(true);

        var anonymizeIP = function (ctx) {
            console.log('Anonymize IP on Segment event', ctx);

            var event = ctx.event;
            event.context = event.context || {};

            event.context.ip = '0.0.0.0';

            return ctx;
        };

        window.analytics.ready(function() {
            console.log('ready', analytics);

            window.analytics.register({
                name: 'IP Anonymizer',
                version: '1.0.0',
                type: 'before',
                isLoaded: function () {
                    return true;
                },
                load: function() {},
                page: anonymizeIP,
                track: anonymizeIP,
                identify: anonymizeIP
            });
        });
        }}();
    </script>

    <button id="trackBtn">Track</button>

    <script>
        document.getElementById("trackBtn").addEventListener('click', function () {
            console.log('click');
            window.analytics.track('btnclick');
        });
    </script>
</body>

</html>
```

The outcome of opening this page in the browser is that the `page` and `identify` events are sent to Segment but no `Anonymize IP on Segment event` console log message is sent (ie. the plugin is not run, and the IPs are not anonymized).

However, clicking the "track" button sends a `track` event to segment with the anonymized IP, and the `Anonymize IP on Segment event console message is fired (ie. the plugin is run).

You can also see in the debug view that the `IP Anonymizer` plugin is not included in the list of events on page load, but is included in the list when the button is clicked.

![Screenshot 2022-09-01 at 15 15 52](https://user-images.githubusercontent.com/377089/187923151-da35194f-00cd-4dd9-9709-31abdc73a242.png)

I believe that this is a bug in the Segment script with how it handles plugins and queued events.
Please could you verify this and look into fixing it?

**Comment by chrisradek** [comment]
@agnieszkaziaja 
Thanks for reporting this! I think there's 2 things we can do here.
1. Halt sending events until any registered plugins are finished loading, like we did with [addSourceMiddleware](https://github.com/segmentio/analytics-next/pull/552)
2. Update the snippet to also allow calling `register` before the library is loaded. You can test this easily yourself by adding the "register" string in the `analytics.methods` array from the snippet. Then `register` should be called before any events are sent.

**Comment by agnieszkaziaja** [comment]
I used the second solution, and everything works now, thank you!
