### ISSUE TITLE
Refused to load the script 'https://cdn.segment.com/next-integrations/integrations/mixpanel/3.2.1/mixpanel.dynamic.js.gz'

### ISSUE THREAD

**Issue by nakul91** [segmentio/analytics-next#595]
Here in my chrome extension -  I am getting these issues not sure what to do I tried updating the Content security policy as well but no luck, Please help me out

s**egmentanalytics.08c9045d.js:27 Refused to load the script 'https://cdn.segment.com/next-integrations/integrations/mixpanel/3.2.1/mixpanel.dynamic.js.gz' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.**

**segmentanalytics.08c9045d.js:27 Refused to load the script 'https://cdn.segment.com/next-integrations/integrations/visual-tagger/0.3.5/visual-tagger.dynamic.js.gz' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.**

**Comment by nakul91** [comment]
@chrisradek  @pooyaj  Please help me out here
i tried adding this as well
 :
"content_security_policy": {
        "extension_pages" :  "script-src 'self' 'wasm-unsafe-eval' ; script-src  'self' 'https://cdn.segment.com/v1/projects/Ja2jQO9engPOdXbtSU6VUAOZgMW67vhJ/settings https://cdn.segment.com/analytics-next/bundles/* https://cdn.segment.com/next-integrations/integrations/*' ; object-src 'self' "
    }

**Comment by zikaari** [comment]
Manifest v3 extensions [no longer support remote scripts](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#remotely-hosted-code).

Your best bet is to package `analytics-next` from NPM into your extension bundle, and then use cloud mode destinations instead.

**Comment by robmerki** [comment]
> Your best bet is to package `analytics-next` from NPM into your extension bundle, and then use cloud mode destinations instead.

Apologies for reopening this issue, but could you explain what you mean by this? How would I go about packaging it into my project?

**Comment by zikaari** [comment]
Like so if your project is vanilla Javascript - https://www.npmjs.com/package/@segment/analytics-next#-using-as-an-npm-package

Like so if it is vanilla + React app - https://www.npmjs.com/package/@segment/analytics-react

Your webpack bundler should take care of the rest.
