### ISSUE TITLE
Q: How access context-fields-automatically-collected data by code (Client Side)?

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [segmentio/analytics-next#596]
I want to send the `ip` and `locale` (Available in `raw` view **automatically collected) inside my  `analytics.track` - What I missing? 
```javascript
analytics.track('generate_lead', {
  course: 'Intro to Analytics',
  title: 'How to Create a Tracking Plan',
  ip, /* how to get the page ip value */
  locale /* how to get the page locale value */
});
```

![image](https://user-images.githubusercontent.com/16711871/190183753-95aa714f-b5c5-442c-bb16-504daad11e69.png)

The same idea for `utm_source` for example (Segment already handle this - how I access this data). 

Related:
https://segment.com/docs/connections/spec/common/#context-fields-automatically-collected

**Comment by pooyaj** [comment]
You can use: 
```
analytics.track("test", {}, {ip: '0.0.0.0', locale: 'en-CA'})
```

**Comment by Ezra-Siton-UIX** [comment]
Your Answer not give any extra details (But you close the topic). 

How i get the values that segment already store? (Not "how to set" values).

**Comment by pooyaj** [comment]
@Ezra-Siton-UIX Segment doesn't store these values. 
- For `locale` it is set here: https://github.com/segmentio/analytics-next/blob/master/packages/browser/src/plugins/segmentio/normalize.ts#L134-L138 
- For `ip` it is not captured client-side. The Segment tracking API sets the IP address unless you explicitly override it client-side

**Comment by Ezra-Siton-UIX** [comment]
OK thanks. My main issue is how to `track` lets say `utm` parmas one time without extra code and `mapping` (Under segment dashboard).

**Comment by rfbowen** [comment]
For what it's worth I'm struggling with a similar issue. I can see where they're [added to the payloads](https://github.com/segmentio/analytics-next/blob/1d505707a95166557d78879abb838babc9eff1e5/packages/browser/src/plugins/segmentio/index.ts#L92) that go out over the network, but I don't appear to be capable of accessing those programmatically anywhere provided by Segment's APIs.

I've played with middleware, event listeners, plugins - all of them appear to omit or obfuscate fields added during this last step. Whenever you inspect the payloads otherwise, they generally only include the 'page' object.

It feels inappropriate that this was closed in the absence of information on how to perform this, or alternatively an admission / clarification that it is not supported.

**Comment by pooyaj** [comment]
Hey folks, let me know if this answers your question: 
- `context.utm` and `context.locale` are added at the last step to the Segment payload, and they can't be intercepted by a plugin. 
- You can override the default value of `context.utm` and `context.locale` using a plugin, by setting those values via plugin. 
- The library doesn't expose a method to access the value of `context.utm` or `context.locale` ( i.e., we don't have `analytics.getUTM()` or `analytics.getLocale()`. The reason we are not offering these methods is to keep the API surface of the library small. Therefore, we are not planning to add these methods in the future either.

**Comment by Ezra-Siton-UIX** [comment]
@pooyaj great answer! thanks. I test again and the mapping under Segment Dashboard works really well (IF someone read this - start by looking on segment reedy made template mapping). 

Thanks

**Comment by rfbowen** [comment]
Thank you for the response @pooyaj - given that you don't intend to expose these to clients, do you have suggestions for the idiomatic way to maintain UTM tracking between client and server?

Ultimately this is going to require I implement redundant UTM parsing in the client, and then send it along in headers with requests to ensure my backend Segment calls can include the UTMs as well. It seems this is something that should be more readily handled or supported by Segment, with exposing those UTMs being one part of that story.

**Comment by pooyaj** [comment]
@rfbowen Right now your best bet is to duplicate this code unfortunately: 
https://github.com/segmentio/analytics-next/blob/2feb0446d43c79aa24d475a6291c8a7b59f6e168/packages/browser/src/plugins/segmentio/normalize.ts#L50-L67

We will look into how we can capture the exact payload sent to Segment ( maybe as a new feature ), but for the time being going with code-duplication is the path forward.
