### ISSUE TITLE
Can't type into event input field

### ISSUE THREAD

**Issue by dcow** [segmentio/analytics-next#598]
I have the tester playground pulled up so I can fire some test events. However, when I try to type anything into the event input field I get errors like:

<img width="1256" alt="Screen Shot 2022-09-19 at 2 34 36 PM" src="https://user-images.githubusercontent.com/547926/191100647-96015677-898a-423f-9928-bd9c0856d898.png">

If I highlight the text box, I see:

<img width="1256" alt="Screen Shot 2022-09-19 at 2 35 15 PM" src="https://user-images.githubusercontent.com/547926/191100802-c1848dfd-a97f-4f1b-8273-1f5c9708a99c.png">

Problem presents on both chrome and safari.

**Comment by chrisradek** [comment]
@dcow Thanks for reporting this. I actually just ran into this issue myself so the timing is perfect - will have a PR to fix this shortly!
