### ISSUE TITLE
undocumented special properties

### ISSUE THREAD

**Issue by guybowden** [segmentio/analytics-next#605]
Not sure if I've missed the docs but we've just spotted an error in our tracking implementation whereby we were tracking an event with properties like `path` and `url`:

```js
analytics.track("Event Name", {path: "/some/path"});
```

This sets the `context.page.path` value to `"/some/path"`

I notice that `title` `url` also set the `context.page` values 

Is this behaviour documented anywhere? I see that the `page` method has this documented, but not `track`
https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#default-page-properties

**Comment by chrisradek** [comment]
@guybowden Thanks for opening this issue. I don't see this behavior documented, but it's coming from our [Page Enrichment](https://github.com/segmentio/analytics-next/blob/4ce49341e3683520465e410acc874755b66d51dc/packages/browser/src/plugins/page-enrichment/index.ts#L104) plugin. It copies those fields to the context when they're available.

Are you looking for a way to turn off this behavior?
