### ISSUE TITLE
'pageunload' does not work on iOS Safari

### ISSUE THREAD

**Issue by jonathan-fielding** [segmentio/analytics-next#607]
Recently we have tried to switch to using batching for our events using Segment analytics.js however we have found that we have lost approx 15% of our events being fired, upon investigation we found this was isolated to the last events being fired on iOS Safari. 

We did some investigation and found that the `pageunload` event is not supported by Safari on iOS. There are a few issues raised on the internet that support this.

* https://stackoverflow.com/questions/4127621/is-there-any-way-to-use-window-onbeforeunload-on-mobile-safari-for-ios-devices
* https://github.com/GoogleChromeLabs/page-lifecycle/issues/11#issuecomment-770031911

The official documentation from Apple https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html shows that they deprecated `pageunload` as well which supports the hypothesis that this won't be fixed.

Interestingly the `pageunload` event does work in Desktop Safari

The suggestion is that instead of using `pageunload` we switch the library to use `pagehide` which has good browser support with Chrome, Edge, Firefox, Opera and Safari having good long term support https://developer.mozilla.org/en-US/docs/Web/API/Window/pagehide_event

I debugged this with @agouil who is going to raise a PR for this change

**Comment by silesky** [comment]
Thank you for bringing our attention to this! It would be great to replace `beforeunload`, but when it comes to simply replacing it with `pagehide` I left a comment here https://github.com/segmentio/analytics-next/pull/608#issuecomment-1267404204
