### ISSUE TITLE
Type for AnalyticsSnippet is missing the `load` function

### ISSUE THREAD

**Issue by vai0** [segmentio/analytics-next#612]
[The snippet](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/quickstart/#step-2-add-the-segment-snippet) contains a defined `load` function which takes a key and options, and injects a script tag and sets the options on `analytics._loadOptions`. Yet `AnalyticsSnippet` is missing the `load` function on it's type. 

https://github.com/segmentio/analytics-next/blob/master/packages/browser/src/browser/standalone-analytics.ts#L5-L9

```typescript
export type AnalyticsSnippet = Analytics & {
  _loadOptions?: InitOptions
  _writeKey?: string
  _cdn?: string
}
```
My use case is we're still using the snippet (not yet AnalyticsBrowser for reasons), but controlling when to call `analytics.load`. 

Would be great if we could include `load` as a type on `AnalyticsSnippet`, e.g.,
```typescript
export type AnalyticsSnippet = Analytics & {
  _loadOptions?: InitOptions
  _writeKey?: string
  _cdn?: string
  load: (writeKey: string, options?: InitOptions) => void
}
```

**Comment by silesky** [comment]
@vai0 This is a good call out;  we would accept a PR for this! Otherwise, I can fix this week.

**Comment by vai0** [comment]
Great — I’ll put up a PR in the next day or so.

**Comment by vai0** [comment]
PR here: https://github.com/segmentio/analytics-next/pull/614
