### ISSUE TITLE
Using this library as a fallback for Expo46 React Native App

### ISSUE THREAD

**Issue by jakescript** [segmentio/analytics-next#625]
There is currently an issue with the segmentio/sovran-react-native library not auto linking in an expo app with sdk46 and Segment is not a supported Expo SDK as of version 46. So in the meantime we were trying to use this package in our Expo app. The package doesnt seem to throw any errors but it is not tracking anything. This just leaves me really curious what is the difference between having this package vs the specific react native package. What does the react native package do that this package does not that makes it work on mobile? Is this package even useable in a react native app? Thanks for the help in advance

**Comment by silesky** [comment]
@jakescript this library contains multiple web APIs (such as window, document) that don't exist in a react native environment, and wasn't designed to work in a react native app.
