### ISSUE TITLE
Analytics 2.0 minified js conflicts with other js libraries

### ISSUE THREAD

**Issue by ivanmgb** [segmentio/analytics-next#627]
Hello,

We are trying to migrate from Analytics 1.0 to the new version(2.0) by following this documentation https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2/.

After inserting the snippet mentioned in the documentation, an error has been seen in the logs when calling analytics.load('API KEY'):

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/86414233/196075660-341d1e54-ffcf-4a94-8a51-95cfb8b7e4cb.png">

We are also using prototype.js version 1.6.0.2. The old Analytics js works with this library.

I tried to play around with it and tried to use the non minified version of Analytics js 2.0 and it works. Is there a no conflict option that we can use so that the minified version will play nicely with prototype js? Since we want to use the minified version for performance. Thank you

This can be replicated using a simple html
`<!DOCTYPE html>
<html lang="en">
<head>

    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
    <script>

        var apiKey = "API KEY";

        !function () {
            var analytics = window.analytics = window.analytics || [];
            if (!analytics.initialize) if (analytics.invoked) window.console && console.error && console.error("Segment snippet included twice."); else {
                analytics.invoked = !0;
                analytics.methods = ["trackSubmit", "trackClick", "trackLink", "trackForm", "pageview", "identify", "reset", "group", "track", "ready", "alias", "debug", "page", "once", "off", "on", "addSourceMiddleware", "addIntegrationMiddleware", "setAnonymousId", "addDestinationMiddleware"];
                analytics.factory = function (e) {
                    return function () {
                        var t = Array.prototype.slice.call(arguments);
                        t.unshift(e);
                        analytics.push(t);
                        return analytics
                    }
                };
                for (var e = 0; e < analytics.methods.length; e++) {
                    var key = analytics.methods[e];
                    analytics[key] = analytics.factory(key)
                }
                analytics.load = function (key, e) {
                    var t = document.createElement("script");
                    t.type = "text/javascript";
                    t.async = !0;
                    t.src = "https://cdn.segment.com/analytics.js/v1/" + key + "/analytics.min.js";
                    var n = document.getElementsByTagName("script")[0];
                    n.parentNode.insertBefore(t, n);
                    analytics._loadOptions = e
                };
                analytics._writeKey = apiKey;
                analytics.SNIPPET_VERSION = "4.15.3";
                analytics.load(apiKey);
                analytics.page();
            }
        }();

    </script>

    <script type="text/javascript" src="http://prototypejs.org/assets/2008/1/25/prototype-1.6.0.2.js"></script>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>`

**Comment by pooyaj** [comment]
@ivanmgb Prototype.js seems to override the native implementation of Array methods with the `prototype.js`'s own implementation, and there is a mismatch between native and prototype JS's method signatures that results in unexpected behavior in libraries that rely on standard method signatures! I think some ["newer"](http://prototypejs.org/2012/08/08/prototype-1-7-1/) versions of prototype.js may have addressed the issue, so upgrading could solve the problem. But long-term, might be a better idea to move away from the obsolete prototype.js library. If upgrading prototype.js or removing it is not a possibility, I recommend staying on Analytics.js 1.0 as we are not going to be compatible with prototype.js.

**Comment by ivanmgb** [comment]
Thank you @pooyaj.
