### ISSUE TITLE
The Segment request failed due to page jumping

### ISSUE THREAD

**Issue by polaris-dxz** [segmentio/analytics-next#648]
In the case of a low-bandwidth network, and the tracking event is accompanied by page jumping, the segment request will fail to report, how should I track the event?

How do you deal with such problems?

**Comment by silesky** [comment]
@polaris-dxz
1. when you say "fail to report" --  you mean it fails to be sent?
2. when you say "page jumping", what exact navigation action do you mean? (e.g. clicking a link to an extreme site -- going back, etc)
3. are you using the npm library or the snippet?
