### ISSUE TITLE
Track function does not pick up Options

### ISSUE THREAD

**Issue by culda** [segmentio/analytics-next#649]
Hi guys, I'm not able to override the context object in the track payload. I've tried the below code among other things and the `context.page` in the payload remains unchanged, filled with the default values.

I'm not using any plugins. I just can't work out how to change the context. 
The properties object works

What am I doing wrong?

```
      void analytics?.track(eventName, properties, {
        context: {
          page: {
            path: '/custom',            
          },
          x: 5,
        },
      });
```

**Comment by culda** [comment]
Found out what it was. 
`properties` was resolving to undefined, essentially making the function call
`track(event, undefined, options)` -> In this case, the options object does not get picked up. 
Passing an empty object instead of undefined does the trick. `track(event, {}, options)`

Is this by design or a bug?

**Comment by silesky** [comment]
Thanks @culda, this looks like a bug.
