### ISSUE TITLE
Inconsistent treatment of integrations object

### ISSUE THREAD

**Issue by allankronmark** [segmentio/analytics-next#653]
Hi guys,

while testing protocols, I was wondering why my `integrations` object (`options.integrations`) kept sending `"All": true`, even when I set `"All": "a test string"` (which should fail the schema validation). 

After much frustration about Protocols and Common JSON Schema and worrying about changes not being applied, I **_finally_** figured out that adding the `integrations` object to the `track` event payload rather than the `load` method worked as expected.

**So in short:**
the `load` method **converts _string_ values** passed on the integrations object **to _boolean_ `true`**. 
-> I believe that to be **incorrect** handling and a **bug**.

**Try it yourself:**
```javascript
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on","addSourceMiddleware","addIntegrationMiddleware","setAnonymousId","addDestinationMiddleware"];analytics.factory=function(e){return function(){var t=Array.prototype.slice.call(arguments);t.unshift(e);analytics.push(t);return analytics}};for(var e=0;e<analytics.methods.length;e++){var key=analytics.methods[e];analytics[key]=analytics.factory(key)}analytics.load=function(key,e){var t=document.createElement("script");t.type="text/javascript";t.async=!0;t.src="https://cdn.segment.com/analytics.js/v1/" + key + "/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n);analytics._loadOptions=e};analytics._writeKey="wuSaCWyTqE6MRDHEFhbD4a7Kz3ccf58J";;analytics.SNIPPET_VERSION="4.15.3";
  const options = {};
  options.integrations = {
      "All": "papa",
      "Test": "bue"
  }
  analytics.load(PASTE_YOUR_WRITEKEY_HERE, options);
  //analytics.page();
  analytics.track('Push Notification Received', {
    "campaign": {
        "medium": "Push",
        "source": "Vendor Name",
        "name": "Referral Flow",
        "content": "Your friend invited you to play a match."
    }
  });
  }}();
```

**Using the example above, the resulting object becomes:**
```javascript
  integrations: {
      "All": true,
      "Test": true
  }
```

**Comment by silesky** [comment]
This behavior is actually by design.

**Comment by allankronmark** [comment]
@silesky thanks for the reply. Well, at least you know. I agree on closing the issue.

The usecase: 
anyone who wants to use the integrations object for consent management purposes might very well wish to require the integrations object via Schema (we wanted to do that). 

The unexpected different treatment on load vs other methods seemed inconsistent and counter-intuitive, but since it's by design, all is good.

Anyway, we've decided that we won't be using the integrations object for consent management purposes. Instead, we're going to rely on the new Destination Filtering (despite the very poor current support for device mode integrations in native apps).

Happy New Year!
