### ISSUE TITLE
Consider publishing pre-releases

### ISSUE THREAD

**Issue by stefanmaric** [segmentio/analytics-next#665]
Hi!

I see a few things queuing up at #642 and I'm particularly interested in #637 while we integrate `@segment/analytics-next`.

I've cloned the repo to test it locally but it would be really helpful to have nightly/alpha/beta/rc tagged versions published to the npm registry before final release, so we don't need to clone & build to start testing new features.

Regardless, thanks for all the efforts.

**Comment by silesky** [comment]
Thanks for the suggestion, we are tracking this internally.
