### ISSUE TITLE
[Question]: How to change cdnURL and analytics.js filename?

### ISSUE THREAD

**Issue by jony1993** [segmentio/analytics-next#696]
Hi there,

We use the [custom domain proxy with cloudfront](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/custom-proxy/#set-up-a-custom-domain-proxy-for-analytics-js). 

**Status quo via the "old" snippet:**
To avoid beeing blocked by AdBlockers we want to rename the `analytics.js` and `analytics.min.js` script filenames to another name. Atm we are still using the "old" snippet and there our code look like this:

```
analytics.load = function (key, options) {
      const script = document.createElement('script')
      script.type = 'text/javascript'
      script.async = true
      script.src = 'https://cdn.analytics.x.de/new_name.js/v1/' +
        key + '/new_name.min.js'

      const first = document.getElementsByTagName('script')[0]
      first.parentNode.insertBefore(script, first)
      analytics._loadOptions = options
    }
```

So `new_name.js` and `new_name.min.js` are our custom script filenames. And on cloudfront we then run a function which replace `new_name.js` with `analytics.js` and `new_name.min.js` with `analytics.min.js`.

**My question for using `analytics-next`**
Is there a way to set the `cdnURL` and also the analytics filename somehow when calling `AnalyticsBrowser.load(...)`?

**Comment by silesky** [comment]
Hey @jony1993. Sorry it's not in the documentation. You can set the CDN like this:

```ts
 AnalyticsBrowser.load({ cdnURL: "my cdn URL" })
 ```

**Comment by silesky** [comment]
@
