### ISSUE TITLE
Unable to add properties at the root level of messages in `@segment/analytics-node`

### ISSUE THREAD

**Issue by lzear** [segmentio/analytics-next#731]
Hello

We are updating from `analytics-node` to `@segment/analytics-node` (because of https://github.com/segmentio/analytics-node/issues/309), and we're facing a small issue that could be worth addressing or documenting: we're placing some custom properties at the root of the tracked events, even though I understand this is not how the API is documented ([docs](https://segment.com/docs/connections/sources/catalog/libraries/server/node/#track)). It was working with `analytics-node` but it breaks with `@segment/analytics-node`.

**(option 1)**: Would it be possible to change `@segment/analytics-node` and `@segment/analytics-core` so extra properties are placed at the root of the tracked object, so there is one less breaking change with `analytics-node`?

**(option 2)** If not, I think it would be beneficial to add warning in [packages/node/README.md](https://github.com/segmentio/analytics-next/tree/master/packages/node#differences-from-legacy-analytics-node--migration-guide) because it's probably not only our team that made this mistake 😄 

---

If option 2 is chosen, the update in [packages/node/README.md](https://github.com/segmentio/analytics-next/tree/master/packages/node#differences-from-legacy-analytics-node--migration-guide) could look like this:

> ## Differences from legacy analytics-node / Migration Guide
>
> [...]
> 
> * Preventing custom properties to be set directly at the root of the event
>   ```ts
>   // old (this was possible even though that is not how the API is documented)
>   analytics.track({
>     userId,
>     event: 'Bookmarked Article',
>     title: 'Moby Dick',
>     author: 'Herman Melville',
>   })
> 
>   // new (custom properties placed on the root will be lost)
>   analytics.track({
>     userId,
>     event: 'Bookmarked Article',
>     properties: {
>       title: 'Moby Dick',
>       author: 'Herman Melville',
>     }
>   })
>   ```

**Comment by silesky** [comment]
@lzear I really appreciate you letting me know about the legacy behavior! I think this is behavior we'd rather not bring over -- The latter "documentation" solution is the right one!
