### ISSUE TITLE
@segment/analytics-node": "^0.0.1-beta.7 / Occasionally, The event was missing.

### ISSUE THREAD

**Issue by ajt1097** [segmentio/analytics-next#733]
For example,
```
workspaceCreated(request: IWorkspaceCreatedRequest): void {
    if (this.env == 'local' || this.env == 'dev') return;

    this.analytics.group(
      {
        userId: request.userId,
        groupId: request.company.companyId,
        traits: {
          name: request.company.companyName,
          avatar: request.company.thumbnailURL
            ? request.company.thumbnailURL
            : undefined,
          management_id: request.company.siteURL,
          creator_name: request.member.name,
          creator_email: request.member.email,
          createdAt: request.company.createdAt,
        },
      },
      (err, ctx) => {
        throw err;
      },
    );

    this.analytics.track(
      {
        userId: request.userId,
        event: SegmentEventEnum.WORKSPACE_CREATED,
        properties: {
          name: request.company.companyName,
          avatar: request.company.thumbnailURL,
          creator_name: request.member.name,
          creator_email: request.member.email,
        },
        context: {
          groupId: request.company.companyId,
        },
      },
      (err, ctx) => {
        throw err;
      },
    );
  }
```
This code must be marked with 'group' and 'track'. However, only one is displayed sometimes and don't throw errors

Is this problem because it's a beta version? Or is there another problem with this code?

**Comment by silesky** [comment]
Under normal conditions, you shouldn't  see errors unless the request fails; when are you getting errors?

If you want to handle any possible errors, the recommendation is to simply
log them globally -- analytics.on("error", console.error)

In your code, don't want to throw errors, as they are happening in callback and are likely not getting caught, which, depending on what you're doing, could either get swallowed or even terminate your whole node process.


For your other question, you should be able to log the context and see the correct events eventually come through in your console. Remember that, by default, the events will take about 10 seconds to send unless the batch is full.

**Comment by silesky** [comment]
@ajt1097 I'm closing this issue since I haven't gotten a response. Feel free to re-open if you are still stuck.
