### ISSUE TITLE
Build fails in Angular when using @segment/analytics-next 1.49.0 

### ISSUE THREAD

**Issue by aribronstein** [segmentio/analytics-next#748]
on the latest version of `@segment/analytics-next` 1.49.0 I am seeing a whole bunch of errors when building my angular app where it seems to be having an issue finding the types.

here is one example of the problem

> Error: Error: node_modules/@segment/analytics-next/dist/types/core/buffer/index.d.ts:57:68 - error TS2307: Cannot find module '@/../../core/dist/types' or its corresponding type declarations.
> 
> 57     identify: (id?: object | import("../user").ID, traits?: import("@/../../core/dist/types").UserTraits | import("@/../../core/dist/types").Callback<import("@/../../core/dist/types").CoreContext<import("@/../../core/dist/types").CoreSegmentEvent>> | null | undefined, options?: import("../events").Options | import("@/../../core/dist/types").Callback<import("@/../../core/dist/types").CoreContext<import("@/../../core/dist/types").CoreSegmentEvent>> | undefined, callback?: import("@/../../core/dist/types").Callback<import("@/../../core/dist/types").CoreContext<import("@/../../core/dist/types").CoreSegmentEvent>> | undefined) => Promise<Context>;
>

**Comment by silesky** [comment]
@aribronstein This should be fixed in 1.49.1 (https://github.com/segmentio/analytics-next/pull/749/files). I've tested on a local angular project. Do you mind validating that this works on your end?

**Comment by aribronstein** [comment]
@silesky works great! thanks for the quick fix.
