### ISSUE TITLE
Export types from `@segment/analytics-node`?

### ISSUE THREAD

**Issue by mpalmerlee** [segmentio/analytics-next#766]
I'm working on integrating the public beta for the `@segment/analytics-node` package (`^0.0.1-beta.15`), it appears that the types for the core method parameters such as `IdentifyParams`, `TrackParams` and `AliasParams` are not exported. It would be nice to be able to use these types in my service so I can more easily type the parameters to my service functions that will call these methods.

**Comment by silesky** [comment]
Fixed in @segment/analytics-node@0.0.1-beta.16!

**Comment by mpalmerlee** [comment]
Thank you for the quick turn around @silesky 🙌 ❗  Confirmed this is working for me and I can now use these types with `0.0.1-beta.16` 🙏
