### ISSUE TITLE
Web worker support

### ISSUE THREAD

**Issue by vibaiher-qatium** [segmentio/analytics-next#771]
Hello!

I'm integrating the segment snippet through @segment/analytics-next package into a React app built with vitejs. It works perfectly when used from React code, but vite is not able to build the distribution files when analytics object is used in a web worker.

It's reporting this error "[vite:worker-import-meta-url] Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.". I don't understand 100% the message, but I guess is related with the way the analytics-next package is distributed.

We are using a wrapper to use the package, that is pretty simpler:

```
import { AnalyticsBrowser, EventProperties } from "@segment/analytics-next";

class Segment {
  private client: AnalyticsBrowser;

  constructor(apiKey: string) {
    this.client = AnalyticsBrowser.load({ writeKey: apiKey });
    this.client.page();
  }

  identify(id: string, email: string) {
    this.client.identify(id, { email });
  }

  track(event: string, properties?: EventProperties) {
    this.client.track(event, properties);
  }

  resetConnection() {
    this.client.reset();
  }
}

export default Segment;
```

Does the package support web workers?

**Comment by silesky** [comment]
This package does not support web workers; it makes heavy fairly heavy use of APIs on the window object; it also loads third party scripts ("device mode"). 

If you don't use any device mode destinations, you can use: 
https://segment.com/docs/api/public-api/

I haven't actually tested it, but the new (beta) of "@segment/analytics-node" should also hypothetically support web workers.

**Comment by silesky** [comment]
I whipped up a partytown.io example that should work with cloud mode integrations and some (but not all) device mode integrations. See: https://github.com/segmentio/analytics-next/pull/773/files#diff-892d1f241b23ff9fb5abb2d6315ecc7e822783c53610490e32792a01f77f7f02

**Comment by vibaiher-qatium** [comment]
Thanks @silesky.

We tried with @segmentio/analytics-node and it worked. Is that also a way?

**Comment by silesky** [comment]
> Thanks @silesky.
> 
> We tried with @segmentio/analytics-node and it worked. Is that also a way?

Yep! Make sure to set "maxEventsInBatch" to 1. 

As long as you don't need device mode destinations, @segment/analytics-node was meant to be usable in any JS runtime that supports fetch.
