### ISSUE TITLE
Automatically add user traits to events in the browser

### ISSUE THREAD

**Issue by RobbeCl** [segmentio/analytics-next#782]
I come from the mixpanel world where we can register super-properties which can be sent automatically with every track method call. I see in the source code that the user is cached within Local Storage and sent with every identify call. Would it be possible to also add these traits to every track request or maybe add some sort of functionality where we can register super properties? Or would this be a bad practice (attributes are implicitly added)?

Thanks!

**Comment by silesky** [comment]
Hi @RobbeCl,

The idiomatic way to set traits is an identity call, which establish a relationship with that user ID that persists as long as that ID is being sent.

https://segment.com/docs/connections/spec/identify/

Does this meet your needs?

**Comment by RobbeCl** [comment]
But when performing an identity call, the succeeding track calls will not be augmented with the identify properties, right? 
I just want to make sure I understand your reply, because you say in your closing sentence "the other way", so I am assuming the first way will also accomplish what I want (which is not the case).

So if I cannot do it with identity calls, the only way to accomplish super properties would be to write a custom plugin?

Thanks for the reply!

**Comment by silesky** [comment]
@RobbeCl 
https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#plugin-architecture

```ts
import { AnalyticsBrowser, Plugin } from "@segment/analytics-next";

const testPlugin: Plugin = {
  name: "My Plugin",
  type: "enrichment",
  version: "0.0.1",
  load: () => Promise.resolve(),
  isLoaded: () => true,
  track: (ctx) => {
    ctx.updateEvent("properties.kiwi", "🥝"); // add property here
    return ctx;
  },
};

export const analytics = new AnalyticsBrowser();
analytics.register(testPlugin);


```

**Comment by RobbeCl** [comment]
Thanks!

**Comment by erickreutz** [comment]
@RobbeCl did you end up writing a plugin? How did you go about accessing the current user traits in said plugin?
