### ISSUE TITLE
Batching does not work after tab switch

### ISSUE THREAD

**Issue by portiz-daitan** [segmentio/analytics-next#783]
I noticed that the batching of events stopped to work when a tab switch occurs in the browser.
I think it's because of the `pageUnloaded` flag that is not being reset to false after `onPageLeave` is called. So, the logic [here](https://github.com/segmentio/analytics-next/blob/0de4a54532a066e7ae7c15e3998d5fc7a91bd2f7/packages/browser/src/plugins/segmentio/batched-dispatcher.ts#L106) will be true, and the flush will be called instead of `scheduleFlush`

**Comment by ericbambach-qwickrate** [comment]
Bump. This is affecting our production install of segment. Is this being looked at at all?

**Comment by silesky** [comment]
This is being worked on https://github.com/segmentio/analytics-next/pull/915
