### ISSUE TITLE
Cannot use "require" to import module 

### ISSUE THREAD

**Issue by Vadorequest** [segmentio/analytics-next#786]
I'm using SWC Spack to bundle my app.

When doing `const AnalyticsBrowser = require('@segment/analytics-next').AnalyticsBrowser`, it breaks the Spack build:

```
thread '<unnamed>' panicked at 'internal error: entered unreachable code: module item found but is_es6 is false: ExportAll(ExportAll { span: Span { lo: BytePos(50081), hi: BytePos(50114), ctxt: #447 }, src: Str { span: Span { lo: BytePos(50095), hi: BytePos(50113), ctxt: #0 }, value: Atom('./core/analytics' type=dynamic), has_escape: false, kind: Normal { contains_quote: true } }, asserts: None })', crates/swc_bundler/src/bundler/chunk/cjs.rs:129:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);

```

I guess the module isn't compatible with ES6, from what I understand of the error.
Is there a way to require the module without using `import`?

**Comment by silesky** [comment]
We do not support using this in a node environment. Please use @segment/analytics-node (package in this repo).

**Comment by Vadorequest** [comment]
@silesky I tried that because I wanted to bypass the limitation of "one Segment integration per app", by connecting to one Segment account using the usual <script> and to another Segment account using the npm package.

But I guess I won't have any luck with that either.

**Comment by silesky** [comment]
@Vadorequest That won't work, as you found out, though not sure what that has to do with using "require", which is a node specific keyword. if you're using 'require' to import AnalyticsBrowser in any context, you're using the library incorrectly and it will not work.

I can just point you back to https://github.com/segmentio/analytics-next/issues/785#issuecomment-1442448328
