### ISSUE TITLE
Why use a React Context?

### ISSUE THREAD

**Issue by IGassmann** [segmentio/analytics-next#791]
The [README of the browser SDK](https://github.com/segmentio/analytics-next/blob/master/packages/browser/README.md) presents a simple and an advanced examples for usage with React. The advanced example uses React Context to provide the SDK to components. What are the advantages of using React Context over loading the SDK once in a module and importing the same instance wherever it is needed as such:

```js
// analytics.js file
import { AnalyticsBrowser } from '@segment/analytics-next'

const analytics = AnalyticsBrowser.load({ writeKey: '<YOUR_WRITE_KEY>' })

export default analytics

// -------------------------

// TrackButton.js file
import analytics from './analytics.js'

const TrackButton = () => {
  return (
    <button onClick={() => analytics.track('hello world')}>
      Track!
    </button>
  )
}
```

**Comment by silesky** [comment]
@imbgar There are no advantages whatsoever, I would highly recommend the simple approach.

**Comment by IGassmann** [comment]
Got it makes sense. Thanks for clarifying.

> We should probably remove the complex context example from our docs.

I think that's a good idea. The advanced example mislead me towards over-engineering my implementation: https://github.com/IGassmann/web-app-template/blob/main/src/features/analytics/AnalyticsContext.tsx

**Comment by silesky** [comment]
README updated!
