### ISSUE TITLE
[node] identify() does not let you set timestamp

### ISSUE THREAD

**Issue by penfold45** [segmentio/analytics-next#796]
Using typescript this code produces no errors
```
analytics.identify({
            userId: '123345',
            timestamp: new Date(),
            traits: {
                name: 'Random name',
            },
        })
```

The api documentation [here](https://segment.com/docs/connections/sources/catalog/libraries/server/node/#identify) also suggests setting timestamp should work. 

However in the code it looks like timestamp is never used or passed through to segment. 
Is there a reason for this? It appears to be passed on all the other calls just not this one.

Thanks

**Comment by silesky** [comment]
Fixed in beta-19
