### ISSUE TITLE
@segment/analytics-node: Analytics not working in Edge Runtime (e.g. Next.js)

### ISSUE THREAD

**Issue by johanneskares** [segmentio/analytics-next#810]
I'm using an edge runtime API function in NextJS (e.g. `pages/api/playground.ts`) Here is a minimal example

```
import { Analytics } from "@segment/analytics-node";
import { NextRequest, NextResponse } from "next/server";

const analytics = () =>
    new Analytics({
        maxEventsInBatch: 1,
        writeKey: process.env.SEGMENT_NODE_API_KEY ?? "",
    }).on("error", console.error);

export default async function handler(request: NextRequest) {
    await new Promise((resolve) => analytics().track({ event: "My Event", userId: "asdf" }, resolve));

    return NextResponse.json({ result: "success" });
}

export const config = {
    runtime: "edge",
};
```

I can't get any analytics into the Node debugger on segment.com. The same is true both for the deployed version on vercel.com as well as the local development version of Next.js

It works for the non-edge version of NextJS (using Lambda)

**Comment by gsheppard** [comment]
Also just went to install the package for use in middleware, and immediately got this error.

```sh
Failed to compile.

../../node_modules/@segment/analytics-node/node_modules/@segment/analytics-core/dist/esm/utils/group-by.js
Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime 
Used by groupBy

Import trace for requested module:
../../node_modules/@segment/analytics-node/node_modules/@segment/analytics-core/dist/esm/queue/event-queue.js
../../node_modules/@segment/analytics-node/node_modules/@segment/analytics-core/dist/esm/index.js
../../node_modules/@segment/analytics-node/dist/esm/app/analytics-node.js
../../node_modules/@segment/analytics-node/dist/esm/index.js
./src/utils/middleware/optimizely.ts
./src/middleware.ts
```

**Comment by ColdSauce** [comment]
Looks like it also doesn't work on the regular (non-Edge) runtime.

**Comment by silesky** [comment]
Thank you for taking out this issue... investigating!

**Comment by johanneskares** [comment]
Thanks so much @silesky for the quick response!

Is there a way for me to test the unmerged feature?

**Comment by silesky** [comment]
Released in `^1.0.0-beta.23`

**Comment by ColdSauce** [comment]
I've tried to get it to work with `1.0.0-beta.23`, but still not getting any events in the Segment debugger, unfortunately. Tried both the snippet in this thread from johanneskares as well as your [`analytics-node-next-13` repo](https://github.com/silesky/analytics-node-next-13/tree/main/pages/api)

Any ideas why?

**Comment by silesky** [comment]
@ColdSauce: I didn't know that repo was on your radar; try pulling from that [analytics-node-next-13 repo](https://github.com/silesky/analytics-node-next-13/tree/main/pages/api) again. I just tested it, and it works

![GIF Recording 2023-03-03 at 10 39 48 AM](https://user-images.githubusercontent.com/5115498/222785765-d012df3f-5991-42e1-bff5-4aabd58682f5.gif)

**Comment by johanneskares** [comment]
Wow @silesky that was super fast. Thanks for adding it in. I can confirm it's working 🚀

**Comment by matheins** [comment]
I had a hard time debugging this. For me the `maxEventsInBatch` setting was missing wich caused the vercel function run into the 10s timeout every time.
