### ISSUE TITLE
Cannot Install library when using Node v18.15.0

### ISSUE THREAD

**Issue by sceptre12** [segmentio/analytics-next#818]
I'm running into this error when I execute: `npm install @segment/analytics-next`
I am using Node v18.15 
npm version: 9.5.0

```
npm ERR! path /node_modules/@stdlib/number-float64-base-normalize
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.15.0 | darwin | x64
.........
.........
.........
npm ERR! gyp info spawn args ]
npm ERR! gyp: binding.gyp not found (cwd: /node_modules/@stdlib/number-float64-base-normalize) while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/.n/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 22.3.0
npm ERR! gyp ERR! command "/Users/.n/bin/node" "/Users/.n/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /node_modules/@stdlib/number-float64-base-normalize
npm ERR! gyp ERR! node -v v18.15.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

```

**Comment by silesky** [comment]
Hey @sceptre12, I wasn't able to reproduce on my local with node 18.15. Can you try pushing a minimal example?

**Comment by jager13579** [comment]
I am also experiencing the same issue with Node 16.20.0 and NPM version 8.19.4. Trying to install also does not find `binding.gyp` and occurs with the same package `@stdlib/number-float64-base-normalize`. It appears to be an issue with the latest 0.0.9 version. If you install version 0.0.8 to your own project, it should install `@segment/analytics-next`.

```
npm i @stdlib/number-float64-base-normalize@0.0.8 --save-dev --save-exact
```

**Comment by silesky** [comment]
@jager13579 @sceptre12 what OS are you guys using?

**Comment by iptpv** [comment]
Hi! I have the same issue. I have to downgrade node to 14 version.

**Comment by sceptre12** [comment]
> I am also experiencing the same issue with Node 16.20.0 and NPM version 8.19.4. Trying to install also does not find `binding.gyp` and occurs with the same package `@stdlib/number-float64-base-normalize`. It appears to be an issue with the latest 0.0.9 version. If you install version 0.0.8 to your own project, it should install `@segment/analytics-next`.
> 
> ```
> npm i @stdlib/number-float64-base-normalize@0.0.8 --save-dev --save-exact
> ```

This works! Thank you
