### ISSUE TITLE
redeclaration of const hideMyLocation

### ISSUE THREAD

**Issue by taidaid** [segmentio/analytics-next#819]
Hello, I've received a Sentry error in my production logs that appears to be related to this package. Do you have any info on this? Thanks!

![image](https://user-images.githubusercontent.com/39394303/225496193-a5ee7811-14d0-4f71-8bbd-5f51fbb83eb2.png)

**Comment by silesky** [comment]
@taidaid `hideMyLocation` is not a variable in any Segment codebase. 😕

**Comment by taidaid** [comment]
@silesky Thanks for the quick response. I noticed that it wasn't present in this repo, I am guessing it's a browser extension or something. Due to the Sentry breadcrumbs, I was just hoping your team knew something about it already. Thanks anyway!
