### ISSUE TITLE
maxRetries does extra request

### ISSUE THREAD

**Issue by mikicho** [segmentio/analytics-next#824]
From what I see [here](https://github.com/segmentio/analytics-next/blob/master/packages/node/src/plugins/segmentio/publisher.ts#L186), if `maxRetreis: 1`, the `maxAttempts = 2` and therefore it enters to the while loop twice instead of once.

**Comment by silesky** [comment]
This appears to be working; next time, please write a failing test rather than just looking at the source code!

**Comment by mikicho** [comment]
@silesky thanks.
Why did you set the maxRetries to 0?

If this is intentional, IMO, this is very counter intuitive.

**Comment by silesky** [comment]
> Why did you set the maxRetries to 0?
Yep; `retries` is much more 'idiomatic' as a setting for an SDK than attempts, which is why it was changed.
