### ISSUE TITLE
Limit the data sent to Segment.io

### ISSUE THREAD

**Issue by rangoo94** [segmentio/analytics-next#829]
We would like to limit the data we are sending to Segment.io, most importantly to not include `context.page.referrer` and `context.page.url`.

We are worried that the referrer may contain sensitive data (i.e. SSO endpoint redirecting to the application). Additionally, because our application may land on internal networks, our users would prefer to not expose the `host` information as well.

Is there a chance to add an option to blacklist some data, like i.e. [**PostHog does**](https://posthog.com/docs/libraries/js#config) with the `property_blacklist` configuration?

Thanks!

**Comment by silesky** [comment]
One way to do this is with a plugin:  https://github.com/segmentio/analytics-next/tree/master/packages/browser#-plugins

**Comment by rangoo94** [comment]
Thank you @silesky! Looks like it's as simple as:

```js
AnalyticsBrowser.load({
  plugins: [{
    name: 'CleanReferrer',
    version: '0.0.0',
    type: 'before',
    isLoaded: () => true,
    load: () => Promise.resolve(),
    track: (ctx) => {
      if (ctx.event.context) {
        ctx.event.context.page.referrer = '';
        ctx.event.context.page.url = '';
      }
      return ctx;
    },
  }],
});
```
