### ISSUE TITLE
Unclear error message when `userId` is numeric - (Error integrating with Auth.js Login Events)

### ISSUE THREAD

**Issue by 0xCLARITY** [segmentio/analytics-next#834]
I was getting the following error: `Must have userId or anonymousId or previousId or groupId`

With a setup like this:
```ts
// [...nextauth].ts

  events: {
    createUser: async (message) => {
      analytics.identify({
        userId: message.user.id,
        traits: {
          email: message.user.email,
        },
      });
    },
    signIn: async (message) => {
      analytics.track({
        userId: message.user.id,
        event: 'Developer Signed In',
      });
    },
```
    
See AuthJS docs on events for audit purposes here: https://next-auth.js.org/configuration/events

Switching back to `analytics-node v6` fixed the issue.

**Comment by silesky** [comment]
Is your ID a string?

**Comment by 0xCLARITY** [comment]
Ah. Yup - that would do it I guess.

**Comment by silesky** [comment]
PR here: https://github.com/segmentio/analytics-next/pull/835
