### ISSUE TITLE
Console error when loading azure-data-lakes next integration

### ISSUE THREAD

**Issue by williav4** [segmentio/analytics-next#851]
I am receiving the following error in my console upon loading the `azure-data-lakes` next integration, and the network request is displaying as failed; however- in my Segment dashboard I appear to be receiving the analytics data from my application just fine. Any idea why I would receive this error despite data flowing? It seems to be an issue with the CDN.

CDN URL returning 404: https://cdn.segment.com/next-integrations/integrations/azure-data-lakes/2.2.4/azure-data-lakes.dynamic.js.gz
Response: `GEThttps://cdn.segment.com/next-integrations/integrations/azure-data-lakes/2.2.4/azure-data-lakes.dynamic.js.gz
[HTTP/2 404 Not Found 631ms] Cannot GET - Invalid path or write key provided.`

Console Message: `Error: Failed to load https://cdn.segment.com/next-integrations/integrations/azure-data-lakes/2.2.4/azure-data-lakes.dynamic.js.gz`

We have verified that the correct write key is being used, and upgraded our code to be using Analytics 2.0 as per the migration documentation. Thanks in advance for any help! :)

**Comment by danieljackins** [comment]
Thanks for the report @williav4! 

This actually isn't a device mode destination and shouldn't be loaded by analytics.js. We'll have this fixed soon.
