### ISSUE TITLE
page tracking doesn't work as intended in v1.15.6 (using CDN), but works in v1.15.4 (using npm)

### ISSUE THREAD

**Issue by ktseo41** [segmentio/analytics-next#853]
### Describe the issue

the library at version 1.15.6 (using the CDN) stopped working as intended. when I reversed the version back to 1.15.4, the issue was resolved. Previously, we tracked pages using the following code snippet:

```js
pageView: function (from, to) {
  window.analytics.page('', to.name, {
    name: to.name,
    path: to.path,
    referrer: from.fullPath,
    search: to.query || undefined,
    title: document.title,
    url: document.href
    // keywords: ''
  })
}
```

we're using vue2, vue-router and we're making the above `pageView` call on every page move in `router/index.js`

### To Reproduce

1. Include the library via CDN with version 1.15.6.
2. Use the provided code snippet for tracking page views.
3. Navigate between pages on the website.
4. Observe that page tracking no longer works as expected.

### Additional context

Please let me know if you need any more information or if there's a new recommended method for tracking page views in v1.15.6. thank you.

**Comment by silesky** [comment]
Hey, @ktseo41 

I think you're missing a URL, correct? `document.href` is not a property -- I think you meant `window.location.href`?

The new behavior means we support proper overriding, so:
```
window.analytics.page('', 'foo, { url: undefined })
```
Will actually result in an object without a URL, rather than us attempting to set a default.
```
  "page": {
            "path": "my path",
            "referrer": "fullPath",
            "search": "query",
            "title": ""
        },
```

If you omit the URL property, this should work as expected.

**Comment by ktseo41** [comment]
@silesky Thanks for your response. first of all, I apologize for the confusion caused by not specifying what result I was expecting. and as you mentioned, I was incorrectly binding the `url`. I have now properly bound the `url`, but our problem has not been resolved.

The issue that occurred in version 1.51.6 is as follows:

Firstly, the page tracking numbers have significantly decreased. below are the results of querying the segment logs being loaded in our service by date:

![image (1)](https://user-images.githubusercontent.com/6429885/237050088-68a91143-91eb-4fae-b39a-0d469e692805.png)

Even after correctly binding the `url` and using the 1.51.6 version through the CDN for page tracking, it still seemed like the page views were decreasing. I wasn't able to verify this properly, but it seemed like the page views were decreasing after deploying to production, so I quickly rolled back and couldn't measure it accurately.

Secondly, some values are missing when viewed in the segment debugger. when tracking with version 1.51.4 via npm, the debugger shows the following:

<img width="397" alt="SCR-20230509-proh" src="https://user-images.githubusercontent.com/6429885/237050592-a4ff0adb-f92e-4632-877c-61c6c5e44621.png">

And below is the result when loading segment with version 1.51.6 (through CDN) and mapping the `url` to location.href. unlike above screenshot, the `name` are not visible. `url` is now displayed correctly

![SCR-20230509-oodc](https://user-images.githubusercontent.com/6429885/237050666-9dc1787c-ff96-4c05-bbed-54341658ce27.png)

The reduced page tracking numbers and the missing `name` values are the issues we are facing when using version 1.51.6.

**Comment by silesky** [comment]
@ktseo41 Thank you for more information.
1. The missing name in the debugger -- I'm having trouble reproing. What does your call look like?

// when I do
```ts
window.analytics.page('ArticlesArticle1', {
    path: 'foo', 
    referrer: 'bar',
    search: 'baz',
    title: 'title',
    url: 'http://foo.com'
  })
```
I get:
<img width="286" alt="image" src="https://github.com/segmentio/analytics-next/assets/5115498/61d84913-1543-420e-930e-1d98bcb8be25">

- Reduced event -- This is vexing; between 1.54-1.56, there's  been no changes to the pipeline that would have affected event velocity. The only big change is a refactor of the page-enrichment plugin, but it wouldn't affect the number of page calls you saw. Are you sure there's been no changes on your end?

https://github.com/segmentio/analytics-next/compare/%40segment/analytics-next%401.51.4...%40segment/analytics-next%401.51.6
