### ISSUE TITLE
How do you disable cookies but preserve localStorage?

### ISSUE THREAD

**Issue by matthew-dean** [segmentio/analytics-next#854]
We'd like to track Segment events, and not set a cookie based on a cookie consent dialog. There's [this documentation](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/persistence/#disable-all-client-side-persistence) that talks about disabling client-side tracking entirely, but that's not what we want. We want to optionally allow Segment to set a cookie, only in certain conditions. How would this be achieved?

**Comment by silesky** [comment]
cc @pooyaj is this possible?

**Comment by silesky** [comment]
This is not possible at the moment apparently. We are tracking it -- we have an internal API that should allows thisz

**Comment by silesky** [comment]
This is now possible: https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/cookie-validity-update/#storage-priority
