### ISSUE TITLE
Clarification question on docs: Do I need to await delayed load function call? 

### ISSUE THREAD

**Issue by petertflem** [segmentio/analytics-next#857]
From the [docs](https://github.com/segmentio/analytics-next/tree/d4dacbd23768af695f659d14e83c95749449bb41/packages/browser#lazy--delayed-loading):
>You can load a buffered version of analytics that requires .load to be explicitly called before initiating any network activity. This can be useful if you want to wait for a user to consent before fetching any tracking destinations or sending buffered events to segment.

Does "buffered version" mean that any `track` or `page` function calls done before calling the `load` function will be sent to Segment after the `load` function has been called and completed? It buffers/stores all `event`/`page` function calls until the `load` function has finished? That is how I interpret the docs, but it is not entirely clear to me when reading it. We lazily initialise the `AnalyticsBrowser` browser when we need it, but haven't awaited anything for the `load` function to finish, which I am wondering if causes a race condition between the initialisation and the tracking.

Slight bonus question: Any version of this package, `@segment/analytics-next`, is considered "Analytics 2.0", right? Just thrown a bit off by the 1.x version.

**Comment by silesky** [comment]
> Does "buffered version" mean that any track or page function calls done before calling the load function will be sent to Segment after the load function has been called and completed?
Correct 😄 
You don't need to await anything -- that's kind of the point, you can treat all the calls as synchronous and analytics will send them when it's ready.

>Any version of this package, @segment/analytics-next, is considered "Analytics 2.0", right? Just thrown a bit off by the 1.x version.
Correct 😄

**Comment by petertflem** [comment]
Awesome thanks! 😁 I also saw this behaviour, is this also what the docs refer to as "buffered"?
1. Click on a link where the click is tracking in the on click handler. The tracking request never gets 200 OK, because the new page (e.g. a completely separated domain) is loaded.
2. When on the new page, navigate back to the previous page.
3. The previous interrupted event is now resent.

**Comment by petertflem** [comment]
I see, as long as it is intended behaviour, not a bug I saw, thanks!
