### ISSUE TITLE
analytics-node issue with memory leak behaviour

### ISSUE THREAD

**Issue by matjam** [segmentio/analytics-next#860]
We use the @segmentio/analytics-node library in a SSR react app (long story, heritage I inherited).

We initialise the library in one place like this;

```js
import { Analytics } from '@segment/analytics-node';

/*
 * Creates an instance of the Segment Analytics library configured with our key.
 *
 * */

const analytics = new Analytics({
  writeKey: OUR_WRITE_KEY_FROM_CONFIG,
  maxEventsInBatch: 1,
});

export default async (req, event) => {
  // log errors we get from the library
  analytics.on('error', (err) => {
    req.log.error({
      message: 'segment-event-failure',
      context: { err, event },
    });
  });

  analytics.track({ ...event });
};
```

The function exported is used to call `track()` so we can catch any errors and log them.

I thought setting `maxEventsInBatch` would avoid this kind of behaviour but since switching to this library we're seeing this. I might resort to initializing the library for every request which would be inefficient. Is there something I missed in the docs here?

<img width="873" alt="image" src="https://github.com/segmentio/analytics-next/assets/578676/5245f3db-1fd2-41f5-86e5-e9cb0da7a448">

**Comment by matjam** [comment]
also, just FYI, I'm not a FE guy but for some reason my team maintains this code and ... here I am. Doing Javascript. Yay.

**Comment by silesky** [comment]
Haha @matjam, I'm sorry for your loss =). Thank you for the report. One thing that sticks out here is that a new emitter is being registered for every event call -- the idea is that the emitter is something global... e.g:

```ts
const analytics = new Analytics({
  writeKey: OUR_WRITE_KEY_FROM_CONFIG,
  maxEventsInBatch: 1,
}).on('error', (err) => {
    req.log.error({
      message: 'segment-event-failure',
      context: { err, event },
    });
});
```

Sorry, I've kind of had to switch gears off this lib or a while.  I actually haven't set up any tooling around testing for memory leaks (this is my fault, but my todo list is long) -- but if you are still having the issue, I will def investigate!

**Comment by matjam** [comment]
yeah, I'll give that a try. I did ship this change, where I call this every time;

```js
    const analytics = new Analytics({
      writeKey: appConfig.BROWSER.SEGMENT.WRITE_KEY,
      maxEventsInBatch: 1,
      flushInterval: 1,
    });

    analytics.on('error', (err) => {
      req.log.error({
        message: 'segment-event-failure',
        context: { err, segmentEvent },
      });
    });

    analytics.track(segmentEvent);
```

And that works around the problem, as awful as it is.

![image](https://github.com/segmentio/analytics-next/assets/578676/266bea44-93be-46b5-b73f-88bb9ad04f8f)

I'll give your second suggestion a try as it makes sense to me to log when the track call errors.

**Comment by silesky** [comment]
Please reopen if not resolved.

**Comment by silesky** [comment]
@nooxx can you share your initialization code?

**Comment by nooxx** [comment]
@silesky I tried initializing once and also on every call:
I also tried with maxEventsInBatch and flushInterval left with default values.

```
const analytics = new Analytics({
      writeKey: this.config.SEGMENT.WRITE_KEY,
      maxEventsInBatch: 1,
      flushInterval: 1,
    });

    analytics.on('error', (err) => {
       ...
    });

    analytics.track(segmentEvent);
```

**Comment by ignaciojcano** [comment]
@nooxx If you are working on NestJS, you'll probably want to create a NestJS Segment Module, in which you would init the Analytics, and then export an AnalyticsService, this should ensure that the module is only instantiated one, and because of this the Analytics initialization only happens once.

Below a quick non tested implementation, that should get you started, there is probably a way to just have the module expose the segment analytics instance directly instead of wrapping it around the service.

```typescript
// segment-analytics/segment-analytics.interfaces.ts
export interface SegmentAnalyticsOptions { // Could potentially just extend Analytics here
  writeKey: string;
  // The other options from Analytics
}

// segment-analytics/segment-analytics.module-definition.ts
import { ConfigurableModuleBuilder } from '@nestjs/common';
import { SegmentAnalyticsOptions } from './segment-analytics.interfaces';

export const { ConfigurableModuleClass, MODULE_OPTIONS_TOKEN } =
  new ConfigurableModuleBuilder<SegmentAnalyticsOptions>().build();

// segment-analytics/segment-analytics.constants.ts
export const SEGMENT_ANALYTICS_INSTANCE = 'SEGMENT_ANALYTICS_INSTANCE'

// segment-analytics/segment-analytics.module.ts
import { Module } from '@nestjs/common';
import { Analytics } from '@segment/analytics-node';
import {
  ConfigurableModuleClass,
  MODULE_OPTIONS_TOKEN,
} from './segment-analytics.module-definition';
import { SegmentAnalyticsService } from './segment-analytics.service';
import { SegmentAnalyticsOptions } from './segment-analytics.interfaces';
import { SEGMENT_ANALYTICS_INSTANCE } from './segment-analytics.constants';

@Module({
  providers: [
    {
      provide: SEGMENT_ANALYTICS_INSTANCE,
      inject: [MODULE_OPTIONS_TOKEN],
      useFactory: (options: SegmentAnalyticsOptions) => new Analytics(options),
    },
    SegmentAnalyticsService,
  ],
  exports: [SegmentAnalyticsService],
})
export class SegmentAnalyticsModule extends ConfigurableModuleClass {}

// segment-analytics/segment-analytics.service.ts
import { Inject, Injectable } from '@nestjs/common';
import { Analytics } from '@segment/analytics-node';
import { SEGMENT_ANALYTICS_INSTANCE } from './segment-analytics.constants';

@Injectable()
export class SegmentAnalyticsService {
  constructor(
    @Inject(SEGMENT_ANALYTICS_INSTANCE)
    private readonly analytics: Analytics,
  ) {}

  async track(opts: any) { // could better define params
    return this.analytics.track(opts);
  }
  
}


// somewhere in your code
// app.module.ts
@Module({
  imports: [
    ConfigModule.forRoot({}),
    SegmentAnalyticsModule.registerAsync({
      useFactory: (config: ConfigService) => ({
        writeKey: config.get('segment.key'),
      }),
      inject: [ConfigService],
    }),
  ],
})
export class AppModule {}

// app.service.ts
@Injectable()
export class AnalyticsService {
  constructor(private readonly analytics: SegmentAnalyticsService) {}
  async someMethod() {
    // do stuff
    await this.analytics.track({ foo: 'bar' });
  }
}
```

**Comment by ignaciojcano** [comment]
I created this package, that might help you https://github.com/ignaciojcano/nestjs-segment-analytics (its pretty much the above)
