### ISSUE TITLE
Broken on sites that include `seedrandom.js`

### ISSUE THREAD

**Issue by dobrynin** [segmentio/analytics-next#863]
There is an ancient script ([seedrandom.js](https://github.com/davidbau/seedrandom)) that is still included in some websites. Unfortunately, improper usage of this script can result in `Math.random` generating consistent outputs, which breaks the uniqueness guarantee of anonymous ID.

Potential solutions:
1. Explicitly check to make sure that Math.random has not been tampered with and handle it somehow.
2. use `@lukeed/uuid/secure` instead of `@lukeed/uuid`, which uses the `crypto` module instead of `Math.random`.
3. use the more common `uuid` library, which is slower but has no reliance on `Math.random` these days.

Note: The website we found that has this issue uses https://github.com/wwwtyro/cryptico which relies on the seedrandom.js script (inlined, not from npm).

**Comment by silesky** [comment]
IIRC We don't use @lukeed/uuid/secure because of browser support -- and forcing users to polyfill crypto don't  help us because the polyfill fallback still uses Math.random.

**Comment by silesky** [comment]
Closing because

**Comment by dobrynin** [comment]
Just was looking into this again and reread your comment @silesky. To be clear our issue is w/ generating anonymous ids, not message ids (re: your comment about hashing the message). iiuc the anonymous id is generated by a direct call to the `@lukeed/uuid` library and so is susceptible to this issue. I understand that this falls under "won't fix" for Segment, but just commenting it here for the record.
