### ISSUE TITLE
Could not resolve '../../lib/get-window' error when bundling with vite 

### ISSUE THREAD

**Issue by sheakelly** [segmentio/analytics-next#878]
Hello, We use vite 2 to bundle our app. I recently attempted to update to the lastest version of `@segment/analytics-next` v1.53.0 and I now get this error running `vite build`
```
Error: Could not resolve '../../lib/get-window' from ../../node_modules/@segment/analytics-next/dist/pkg/core/analytics/index.js
```
Looking at the `index.js` file it has no reference to a `../../lib/get-window` module. I ran grep across my whole codebase and could not find `get-window` anywhere. 

FWIW the newest version of the library that does work is 1.38.0. I have also tried vite v4 and got the same error.

Any help here would be greatly appreciated.

**Comment by silesky** [comment]
Hmm, not a method that we use either. We have a vite example that builds without errors in our CI: https://github.com/segmentio/analytics-next/tree/master/examples/with-vite

**Comment by silesky** [comment]
Stale
