### ISSUE TITLE
New example with nextjs app?

### ISSUE THREAD

**Issue by sathishkannan162** [segmentio/analytics-next#886]
Can you anybody add an example for new nextjs app router? 
I am a beginner and would like to see an example with new nextjs app router.

**Comment by silesky** [comment]
Hey @sathishkannan162, I have something like this in the works for our repo that will use next 13.

There is also a new example in review on vercel. 

https://github.com/vercel/next.js/pull/52327#discussion_r1277490268

**Comment by iljapanic** [comment]
Hey @silesky, have there been any updates on this?

Would love to use the recommended Next.js app router implementation rather than embarking on a DIY approach.

**Comment by sathishkannan162** [comment]
> Hey @sathishkannan162, there is a new example in review on vercel. Once it gets merged in, I will be linking to it in our README.
> 
> [vercel/next.js#52327](https://github.com/vercel/next.js/pull/52327)

Great. Thank you

**Comment by silesky** [comment]
Yes @iljapanic, the examples are ready:
 1. https://github.com/vercel/next.js/tree/canary/examples/with-segment-analytics
 2. https://github.com/vercel/next.js/tree/canary/examples/with-segment-analytics-page-router 
 3.

**Comment by iljapanic** [comment]
Thank you for a quick response @silesky! The example works great and is super easy to implement 🙌

**Comment by silesky** [comment]
@iljapanic Thank you! I also updated the README: https://github.com/segmentio/analytics-next/tree/master/packages/browser#nextjs
