### ISSUE TITLE
`analytics.identify` sends traits through `context` when userId is null (version 1.53.0)

### ISSUE THREAD

**Issue by seg-leonelsanches** [segmentio/analytics-next#909]
On version 1.53.0, I tested with a client the following call:

```js
analytics.identify(null, {
   prop1: 1,
   prop2: "2"
});
```

The properties will go to `context` payload in Segment, instead of `traits`.

The problem doesn't happen in version 1.52.0. I advised the client to downgrade the library.

**Comment by silesky** [comment]
Sore, I'm unable to repro this.

**Comment by seg-leonelsanches** [comment]
Hi @silesky. We got to reproduce also in 1.52.0. The customer is not using userId, but another column called CPF (it's like the SSN for Brazil):

<img width="1918" alt="image" src="https://github.com/segmentio/analytics-next/assets/113376080/9e413f09-e2c6-4808-98bd-6d3c2ce4132c">
