### ISSUE TITLE
How to trigger `analytics.screen`? 

### ISSUE THREAD

**Issue by lhrinaldi** [segmentio/analytics-next#911]
Hello there!

Does `analytics.screen` needs to be used in a different way to be triggered? I try to track the same event both with `screen` and `track`.

`track` works correctly, triggers the request, but not `screen`. Am I missing something? I'm calling them in the same manner.

**Comment by chrisradek** [comment]
@lhrinaldi 
We actually just fixed an issue where screen events weren't getting fired:
https://github.com/segmentio/analytics-next/releases/tag/%40segment%2Fanalytics-next%401.53.1

I don't believe we've rolled this out to the CDN yet, but it is available on NPM.

**Comment by lhrinaldi** [comment]
Thanks for the response @chrisradek , I've installed this version, but unfortunately it yet doesn't trigger screen events. At least no logs are being written by the Sprig lib in the console.

**Comment by silesky** [comment]
@lhrinaldi analytics.screen() works for me:



<img width="982" alt="image" src="https://github.com/segmentio/analytics-next/assets/5115498/dc9a2a63-23f5-44f4-88b9-b90b22524d60">

in the debugger:
![image](https://github.com/segmentio/analytics-next/assets/5115498/1befe75b-700f-4525-a65b-1e67012cc4bd)

**Comment by lhrinaldi** [comment]
@silesky 

I'm currently using the `analytics-next` npm package. Just confirmed and its the version `1.53.2`. 

![image](https://github.com/segmentio/analytics-next/assets/1268808/a72c8602-eb64-4e70-ac14-09c8a4430fbf)

I'm not sure how to provide you guys more useful information, please let me know if there is some debugging I can do to help with this. 

---

### Current code

About the code, the screen function is called inside an `useEffect` hook and it looks like this:

```
 useEffect(() => {
    if (!isVisible) return;

    const [, rootPath] = pathname.split("/");
    const uiScreen = {
      course: "learn",
      explore: "explore",
    }[rootPath ?? ""];

    Analytics.provider.screen(
      Analytics.Event.Payments.Viewed,
      {
        offer_price: offerPrice,
        trial_is_shown: trialIsShown,
        ui_screen: uiScreen,
      }
    );
  }, [isVisible, pathname, offerPrice, trialIsShown]);
```

`provider.screen` is the following function, where `analyticsBrowser` was assigned the return of calling `AnalyticsBrowser.load`.

```
screen(eventName: string, payload?: Object) {
    this.analyticsBrowser.screen(eventName, payload);
  }
```

### Assumptions

I'm currently assuming that `screen` is not working because in `Sprig debug mode` nothing gets logged to the console, and in turn, if I change the `screen` call for `track` it gets logged correctly.

**Comment by lhrinaldi** [comment]
It's working.
