### ISSUE TITLE
How to trigger manually flush of batch event

### ISSUE THREAD

**Issue by philibea** [segmentio/analytics-next#913]
Hey Segment Team,

I would like to know if it's possible to expose the flush function to manually trigger the flush of batch events ? 

Code source of the flush: 
https://github.com/segmentio/analytics-next/blob/a9a923a7bbcd36f2e42a36bf3def9825ff65300f/packages/browser/src/plugins/segmentio/batched-dispatcher.ts#L73

Thanks

**Comment by silesky** [comment]
It's not possible; what's the exact use case for this that ours targeting? Is this for testing?

**Comment by philibea** [comment]
> It's not possible as you noticed; what's your use case?

@silesky 
My use case:  we have an issue with Amplitude plugin actually and we think that the issue is related how we send request to Segment and how it's treat by Amplitude.

I don't want to remove batch events from my configuration, and i think if we have flush we can mix between 'standard' | 'batch' because we can flush between a Track and Group call and send 2 requests network for theses events.

**Comment by kim5566** [comment]
+1 could we flush on demand? this is also align with other segment backend library like java. node client should support flush without refusing to add new events.

**Comment by silesky** [comment]
Thanks for the feedback! We tracking this issue here: https://github.com/segmentio/analytics-next/issues/822
