### ISSUE TITLE
Why is segment injecting intercom into my website?

### ISSUE THREAD

**Issue by nandorojo** [segmentio/analytics-next#920]
Segment is loading an intercom script into my website. I never configured this. It's making our intercom pop up on our site when we don't want it to. I disabled the integration on segment, and I disabled the launcher on intercom, but it's still happening. How can I disable this? And why is this the default behavior?

**Comment by silesky** [comment]
@nandorojo 
We don't do inject any scripts like Intercom by default; this is not an SDK related issue. Please contact Segment support.

**Comment by nandorojo** [comment]
Thanks for the reply.

This library certainly is loading an intercom script. Removing this code removes the intercom script:

```
AnalyticsBrowser.load({
  writeKey: …
})
```

and this makes me think it is coming from the SDK, given that it says `next-integrations`.

<img width="527" alt="image" src="https://github.com/segmentio/analytics-next/assets/13172299/8c669635-0775-4848-9556-1159db1d72a6">

The moment I call `load()` from `@segment/analytics-next`, I see intercom.

I spun up a new site and tried there. Same issue. Changing the keys to a different Segment account hides the Intercom integration.

Removing the integration fixed it, but I was surprised that Segment would be injecting scripts like that, even if the site doesn’t have intercom’s JS on it.

Happy to privately share the writeKey which causes this to happen if you want to repro it on your end.

**Comment by silesky** [comment]
The SDK is certainly meant to inject scripts that you have specifically configured if you are using "device mode" integrations. If you only use cloud mode destinations, we don't inject anything. https://segment.com/docs/connections/destinations/
