### ISSUE TITLE
The setAnonymousId promise never resolves when called before load

### ISSUE THREAD

**Issue by jfroelich** [segmentio/analytics-next#921]
Using latest npm lib in a node project (that transpiles to browser via webpack).

```js
import * as Segment from '@segment/analytics-next';

async function foo() {
  const analytics = new Segment.AnalyticsBrowser();
 
  // this promise never resolves so this await is stuck
  await analytics.setAnonymousId('1234');

  // this never runs because the previous promise is stalled
  await analytics.load(...);
}
```

Calling setAnonymousID after load works just fine:

```js
import * as Segment from '@segment/analytics-next';

async function foo() {
  const analytics = new Segment.AnalyticsBrowser();
  await analytics.load(...);
  await analytics.setAnonymousId('1234');
}
```

This was a pretty confusing thing to figure out because it seems like I should be able to set anonymous id whenever. The docs are not sufficiently clear here. It is also not entirely clear why setAnonymousId is a promise returning function.

**Comment by silesky** [comment]
@jfroelich Hey, thanks for taking this issue.

I understand it's a bit confusing -- but you shouldn't ever need to await `analytics.load` or `setAnonId`. That's not an example we provide on our side (the await analytics.load is useful for testing, but I would never rec using it unless you're doing something very wonky). 

`setAnonId` resolves when load is complete -- so it makes sense that if you await for it and then await load, it never resolves. This creates a lock.

 I agree with you, maybe it shouldn't resolve to a promise -- but it's kind of hard to change the API at this point -- once you understand that all of these buffered events resolve when flush is complete, it's a lot simpler.

**Comment by jfroelich** [comment]
Thank you for the response. I understand. We have a convention of no unawaited promises. We also have a convention of not using promise returning functions when there is no callback or next tick stuff happening. So there was some friction here. Perhaps it would be nice to change the api to not expose promise returning functions when in fact nothing promise-related is involved. In the meantime, your answer addressed my concerns and is much appreciated. I am closing this then, assuming that is ok. Thank you again.
