### ISSUE TITLE
ReferenceError: getGlobalCDNUrl function window is not defined

### ISSUE THREAD

**Issue by altyntsevlexus** [segmentio/analytics-next#926]
Hello! We've moved to the 2.0 version and started receiving errors in Sentry - `getGlobalCDNUrl(@segment.analytics-next.dist.cjs.lib:parse-cdn) window is not defined.`

The problem is inside `getGlobalCDNUrl` function.

<img width="917" alt="image" src="https://github.com/segmentio/analytics-next/assets/60012511/52d1aebe-3406-4e83-8f73-2600515613a0">

**Comment by altyntsevlexus** [comment]
@silesky I understand that I can fix it with `window` check, however, in next js [example](https://github.com/segmentio/analytics-next/blob/4da83396e47b94421b2ede5253654e73c9109db1/examples/with-next-js/context/analytics.tsx) there is no `window` check. Maybe, I am missing something.

**Comment by silesky** [comment]
@altyntsevlexus ensure that .load is not called on the server in whichever way you choose.

some additional next.js examples are here: https://github.com/vercel/next.js/pull/52327
