### ISSUE TITLE
Track method missing events in source debugger

### ISSUE THREAD

**Issue by aleczratiu** [segmentio/analytics-next#955]
Hello,

Following the documentation I'm using @segment/analytics-node: 1.1.0 on my node server, the problem I face is if my track method gets called 15 times in segment dashboard / sourced / debugger, sometimes are 10 events other times 15 or fewer depending, I can't find a pattern or a way to fix this issue. I'm not sure if this issue is only on my side but it's very frustrated and I didn't find yet a solution for this.

Having a function inside of it I have the track method.

```
const { segmentProperties, eventName, payload } = data;
const { teamId, anonymousId, userId, ...rest } = segmentProperties || {};

analytics.track({
      anonymousId,
      userId: userId.toString(),
      event: eventName,
      properties: payload,
      context: {
          ...(rest || {}),
          ...(teamId && { group: { id: teamId.toString() } }),
      },
  });
```

The Segment sdk initialization is outside of the function context to be initialized once for all the calls.

```
const analytics = new Analytics({
    writeKey: configContents.segment.apiKey,
});
```

- I've tried the batch with big number or with 1 or default, flush queue with a long time with less time or default, many options combined or tested but without any luck. 
- As a note I've tried also an old version analytics-node 6.0.0 but with the same behavior.

Could someone guide me if I missed something or could be an issue?

The module I use: @segment/analytics-node: 1.1.0

**Comment by silesky** [comment]
@aleczratiu the debugger is just a sampling of events.

**Comment by aleczratiu** [comment]
> @aleczratiu the debugger is just a sampling of events, it doesn't contain every event. If you want to view every event, see your data warehouse.
> 
> https://segment.com/docs/connections/sources/debugger/

Many thanks @silesky for your time! Much clearer and makes sense now.
