### ISSUE TITLE
Missing return types and promises not awaited

### ISSUE THREAD

**Issue by thehme** [segmentio/analytics-next#961]
I have added this package to my ts project and seeing these errors on compile:

```
node_modules/@segment/analytics-node/src/app/analytics-node.ts(97,11): error TS7010: '_dispatch', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/@segment/analytics-node/src/lib/abort.ts(63,40): error TS7011: Function expression, which lacks return-type annotation, implicitly has an 'any[] | readonly [AbortSignal | AbortSignal, Timeout]' return type.
node_modules/@segment/analytics-node/src/plugins/segmentio/publisher.ts(178,39): error TS2339: Property 'message' does not exist on type '{ success: true; } | { success: false; message: string; }'.
  Property 'message' does not exist on type '{ success: true; }'.
```

I can try to fix these errors, which lead to errors about promises not being awaited in `packages/node/src/app/analytics-node.ts`. I think I have fixed these errors too, so would like to post a PR and get any feedback necessary. This is blocking us from using the package to start tracking server side events.

**Comment by silesky** [comment]
These errors do not show up for us, we are using TS 4.x. I assume you are using a later version of Typescript.

Can you set "skipLibCheck: true" in your tsconfig?

**Comment by silesky** [comment]
@thehme:
`As for using skipLibCheck: true, I tried this before and still got the same errors.`

That shouldn't be the case -- getting any errors in node_modules is a sign that this isn't working =S

**Comment by thehme** [comment]
I am working on a sample repo.

**Comment by thehme** [comment]
@silesky I worked on the sample repo and found the issue. My IDE (VS Code v1.82.2) imported types as follows in the non-working project:

```
import {
  IdentifyParams,
  PageParams,
  TrackParams
} from "@segment/analytics-node/src/app/types";
```
When I created a clean repository, the types were imported differently:

```
import {
  IdentifyParams,
  PageParams,
  TrackParams
} from "@segment/analytics-node";
```

Without the sub-directories, the compilation errors went away. The errors were due to how the types were being imported.
