### ISSUE TITLE
Segment is not loaded when OneTrust consent integration is setup and jurisdiction does not require a banner to be shown. 

### ISSUE THREAD

**Issue by backjo** [segmentio/analytics-next#972]
In https://github.com/segmentio/analytics-next/blob/1eaef11131e038996860441a6f0863ce89663668/packages/consent/consent-wrapper-onetrust/src/domain/wrapper.ts#L48 , Segment's consent-wrapper for OneTrust checks for `oneTrustGlobal.IsAlertBoxClosed()`. This function will not return true unless a user has explicitly confirmed / set their privacy settings. While this is desirable in jurisdictions like US-CA and the EU, some jurisdictions do not require a banner to first be shown and thus many users will not explicitly set a privacy setting with OneTrust - preventing the Segment SDK from ever being loaded for that user. 
<img width="910" alt="Screenshot 2023-10-16 at 5 47 23 PM" src="https://github.com/segmentio/analytics-next/assets/2441427/fc756ea3-0860-4df1-a9a4-3c9f53d56e67">

**Comment by silesky** [comment]
Thanks, @backjo for taking out an issue. 

Do you mind telling me how to find that "Show Banner" setting in OneTrust, so I can reproduce? I'm having trouble finding it in the OT UI.

**Comment by silesky** [comment]
Thanks @backjo for reporting. I have been unable to identify a workaround and have contacted OneTrust about this behavior / bug.

**Comment by backjo** [comment]
Thx @silesky - if it's a larger fix that is needed, it might be useful just to let a consumer of this library drive this behavior via a configuration property on the OneTrustSettings

**Comment by silesky** [comment]
@backjo good news, I have a PR up (#987)

Just confirming: you have default categories (e.g CAT001, etc) set up that will always be active for the jurisdictions in question, correct, unless they explicitly opt out by interacting with the modal?
