### ISSUE TITLE
OneTrust integration - support a required group for loading a.js 

### ISSUE THREAD

**Issue by backjo** [segmentio/analytics-next#977]
Opening this issue to discuss a potential contribution - would love input from the Segment team here!

As a user wanting to implement Segment in a compliant way with GDPR, CCPA and the ever-growing set of privacy regulations, it would be convenient if I could load Segment if and only if a user has consented to some level of tracking. While it is possible to implement this requirement outside of a.js, with the new OneTrust integration for privacy consent management, it would be really convenient to just tell the OneTrust wrapper the group(s) it requires before even loading a.js and dropping cookies.

**Comment by silesky** [comment]
Thanks @backjo: We actually have plans this quarter to do something that sounds quite similar.

We will not load segment at all if:
* Workspace has no unmapped destinations AND
* User has not consented to any categories defined in the workspace 


In addition, we also have settings in the lower level library that we can easily expose:
We also have the following settings in the lower level library that might be useful to expose:
https://github.com/segmentio/analytics-next/blob/2f1ae75896123e0aeaa1608fde15312adddd5614/packages/consent/consent-tools/src/types/settings.ts#L74

**Comment by backjo** [comment]
Hey @silesky - not yet, was going to bring it up on slack w/ product, glad to hear y'all are thinking about it. I'll follow up with the team there :)

One important thing to consider is that one of the active groups (categories) may be something like "Strictly Essential Cookies" and may always be present - so some minimal configurability there would be really helpful!

**Comment by silesky** [comment]
> One important thing to consider is that one of the active groups (categories) may be something like "Strictly Essential Cookies" and may always be present

Yep, that's definitely a core scenario that we plan to support with our updates.
