### ISSUE TITLE
 support flush on demand for node.js client

### ISSUE THREAD

**Issue by kim5566** [segmentio/analytics-next#988]
hey team,

i'm wondering if node.js client could support flush on demand like the classic one does before,
```
analytics.flush(function(err, batch){
  console.log('Flushed, and now this program can exit!');
});
```

instead of call `.closeAndFlush()`  to stop collecting new events.

The use case i have is, i have set flushAt, for example, 100 and let batch processing events.

There's one particular time sensitive event, when it fired, i want to send immediately instead of waiting for the batch. 

But i still want to keep collecting new events after flush.

**Comment by silesky** [comment]
Hey, we are looking at bringing this back -- see https://github.com/segmentio/analytics-next/issues/822

**Comment by silesky** [comment]
Tracking this: https://github.com/segmentio/analytics-next/issues/822
